# q3.rq — http://www4.wiwiss.fu-berlin.de/bizer/BerlinSPARQLBenchmark/spec/index.html#queryTripleQ3
# $Id: q3.rq,v 1.3 2008-11-16 14:06:36 eric Exp $
# 
# substitutions:
#   %ProductType%=<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType59>
#   %ProductFeature1%=<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature5>
#   %ProductFeature2%=<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature7>
#   %x%=66
#   %y%=84

PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?product ?label
WHERE {
 ?product rdfs:label ?label .
 ?product a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductType59> .
	?product bsbm:productFeature <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature5> .
	?product bsbm:productPropertyNumeric1 ?p1 .
	FILTER ( ?p1 > 66 ) 
	?product bsbm:productPropertyNumeric3 ?p3 .
	FILTER (?p3 < 84 )
 OPTIONAL { 
 ?product bsbm:productFeature <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature7> .
 ?product rdfs:label ?testVar }
 FILTER (!bound(?testVar)) 
}
ORDER BY ?label
LIMIT 10
