SELECT ?patient ?dob ?sex ?takes ?indicDate 
WHERE
{
  {
    ?patient <http://hospital.example/DB/Person#MiddleName> ?middleName .
    ?patient <http://hospital.example/DB/Person#DateOfBirth> ?dob .
    ?patient <http://hospital.example/DB/Person#SexDE> ?sexEntry_gen0 .
    ?sexEntry_gen0 <http://hospital.example/DB/Sex_DE#EntryName> ?sex .
    ?indicItem_gen2 <http://hospital.example/DB/Item_Medication#PatientID> ?patient .
    ?indicItem_gen2 <http://hospital.example/DB/Item_Medication#PerformedDTTM> ?indicDate .
    ?indicItem_gen2 <http://hospital.example/DB/Item_Medication#EntryName> ?takes .
    ?indicMed_gen3 <http://hospital.example/DB/Medication#ItemID> ?indicItem_gen2 .
    ?indicMed_gen3 <http://hospital.example/DB/Medication#DaysToTake> ?indicDuration_gen4 .
    ?indicMed_gen3 <http://hospital.example/DB/Medication#MedDictDE> ?indicDE_gen5 .
    ?indicDE_gen5 <http://hospital.example/DB/Medication_DE#NDC> ?indicNDC_gen6 .
    ?indicCode_gen1 <http://hospital.example/DB/NDCcodes#NDC> ?indicNDC_gen6 .
    ?indicCode_gen1 <http://hospital.example/DB/NDCcodes#ingredient> ?code .
    FILTER ( ?code = 6809  || ?code = 6810 )
  }
  OPTIONAL {
        ?indicItem_gen3 <http://hospital.example/DB/Item_Medication#PatientID> ?patient .
        ?indicItem_gen3 <http://hospital.example/DB/Item_Medication#PerformedDTTM> ?indicDate .
        ?indicMed_gen4 <http://hospital.example/DB/Medication#ItemID> ?indicItem_gen3 .
        ?indicMed_gen4 <http://hospital.example/DB/Medication#DaysToTake> ?indicDuration_gen5 .
        ?indicMed_gen4 <http://hospital.example/DB/Medication#MedDictDE> ?indicDE_gen6 .
        ?indicDE_gen6 <http://hospital.example/DB/Medication_DE#NDC> ?indicNDC_gen7 .
        ?indicCode_gen2 <http://hospital.example/DB/NDCcodes#NDC> ?indicNDC_gen7 .
        ?indicCode_gen2 <http://hospital.example/DB/NDCcodes#ingredient> ?contCode .
        FILTER ( ?contCode = 11289  || ?contCode = 11290 )
  }
  FILTER ( !bound(?contCode))
}
LIMIT 30
