PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX Person: <http://hospital.example/DB/Person#>
PREFIX Sex_DE: <http://hospital.example/DB/Sex_DE#>
PREFIX Item_Medication: <http://hospital.example/DB/Item_Medication#>
PREFIX Medication: <http://hospital.example/DB/Medication#>
PREFIX Medication_DE: <http://hospital.example/DB/Medication_DE#>
PREFIX NDCcodes: <http://hospital.example/DB/NDCcodes#>

SELECT ?patient ?dob ?sex ?takes ?indicDate 
WHERE
{
  {
    ?patient Person:MiddleName ?middleName ;
             Person:DateOfBirth ?dob ;
             Person:SexDE ?_sex_0_sexEntry .
    ?_sex_0_sexEntry Sex_DE:EntryName ?sex .
    ?_person2drug_0_itemMed Item_Medication:PatientID ?patient ;
                            Item_Medication:PerformedDTTM ?indicDate ;
                            Item_Medication:EntryName ?takes .
    ?_person2drug_0_medication Medication:ItemID ?_person2drug_0_itemMed ;
                               Medication:DaysToTake ?_person2drug_0_medDuration ;
                               Medication:MedDictDE ?_person2drug_0_medDE .
    ?_person2drug_0_medDE Medication_DE:NDC ?_person2drug_0_medNDC .
    ?_person2drug_0_medCodes NDCcodes:NDC ?_person2drug_0_medNDC ;
                             NDCcodes:ingredient ?indicCode .
      FILTER ( ?indicCode = 6809  || ?indicCode = 6810 )
  }
  OPTIONAL     {
      ?_person2drug_1_itemMed Item_Medication:PatientID ?patient ;
                              Item_Medication:PerformedDTTM ?indicDate ;
                              Item_Medication:EntryName ?takes_gen1 .
      ?_person2drug_1_medication Medication:ItemID ?_person2drug_1_itemMed ;
                                 Medication:DaysToTake ?_person2drug_1_medDuration ;
                                 Medication:MedDictDE ?_person2drug_1_medDE .
      ?_person2drug_1_medDE Medication_DE:NDC ?_person2drug_1_medNDC .
      ?_person2drug_1_medCodes NDCcodes:NDC ?_person2drug_1_medNDC ;
                               NDCcodes:ingredient ?contraCode .
      FILTER ( ?contraCode = 11289  || ?contraCode = 11290 )
    }
  FILTER ( !bound(?contraCode) )
}

LIMIT 30
