# opt1
# from http://www.w3.org/2008/07/MappingRules/#opt1 Revision: 1.38 
# $Id: query_spec-opt1.rq,v 1.1 2008-09-08 13:12:40 eric Exp $

PREFIX emplP: <http://hr.example/DB/Employee#>

SELECT ?empName ?birthday
 WHERE { ?emp      emplP:lastName   ?empName .
         OPTIONAL { ?emp      emplP:birthday   ?birthday } }
