# q11.rq — http://www4.wiwiss.fu-berlin.de/bizer/BerlinSPARQLBenchmark/spec/index.html#queryTripleQ11
# $Id: q11.rq,v 1.1 2008-11-10 05:13:41 eric Exp $
# 
# substitutions:
#   %OfferXYZ%=http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromVendor3/Offer2920

SELECT ?property ?hasValue ?isValueOf
WHERE {
 { http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromVendor3/Offer2920 ?property ?hasValue }
 UNION
 { ?isValueOf ?property http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromVendor3/Offer2920 }
}
