# ruleMap.rq — SPARQL CONSTRUCT version of
#   http://www4.wiwiss.fu-berlin.de/bizer/BerlinSPARQLBenchmark/results/store_config_files/d2r-mapping.n3
# $Id: ruleMap.rq,v 1.3 2008-11-13 19:18:01 eric Exp $
# 
# antecedents are SQLizable using the stem http://bsbm.example/db .

PREFIX map: <file:/E:/code/d2r-server-0.4/d2r-mapping.n3#>
PREFIX db: <>
PREFIX vocab: <vocab/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX d2rq: <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rev: <http://purl.org/stuff/rev#>

PREFIX offer: <http://bsbm.example/db/offer#>
PREFIX person: <http://bsbm.example/db/person#>
PREFIX producer: <http://bsbm.example/db/producer#>
PREFIX product: <http://bsbm.example/db/product#>
PREFIX productfeatureproduct: <http://bsbm.example/db/productfeatureproduct#>
PREFIX producttypeproduct: <http://bsbm.example/db/producttypeproduct#>
PREFIX productfeature: <http://bsbm.example/db/productfeature#>
PREFIX producttype: <http://bsbm.example/db/producttype#>
PREFIX review: <http://bsbm.example/db/review#>
PREFIX vendor: <http://bsbm.example/db/vendor#>

PREFIX tr: <http://www.w3.org/2008/04/SPARQLfed/#>

CONSTRUCT {
tr:bind(?offer, bsbm-inst:, "dataFromVendor$(offer_publisher)/Offer$(offer_nr)")
       a bsbm:Offer ;
       bsbm:product ?product ;
       bsbm:vendor ?vendor ;
       bsbm:price ?lit_price ; # bsbm:USD
       bsbm:validFrom ?lit_validFrom ; # xsd:date
       bsbm:validTo ?lit_validTo ; # xsd:date
       bsbm:deliveryDays ?lit_deliveryDays ; # xsd:int
       bsbm:offerWebpage ?lit_offerWebpage ; # unknown!
       dc:publisher ?vendor ;
       dc:date ?offer_publishDate . # xsd:date

?person a foaf:Person ;
        foaf:name ?lit_name ;
        foaf:mbox_sha1sum ?lit_mbox_sha1sum ;
	d2rq:belongsToClassMap map:person ;
	bsbm:country ?perCountry ;
	dc:publisher ?perPublisher ;
        dc:date ?per_publishDate . # xsd:date

?producer a bsbm:Producer ;
          rdfs:label ?prod_label ;
          rdfs:comment ?prod_comment ;
          foaf:homepage ?prod_homepage ;
          bsbm:country ?prodCountry ;
	  dc:publisher ?prodPublisher ;
          dc:date ?prod_publishDate . # xsd:date

?product a bsbm:Product ;
         bsbm:productFeature ?pfp ;
         rdf:type ?ptp ;
         rdfs:label ?p_label ;
         rdfs:comment ?p_comment ;
         bsbm:producer ?producer ;
         bsbm:productPropertyNumeric1 ?lit_propertyNum1 ; # xsd:int
         bsbm:productPropertyNumeric2 ?lit_propertyNum2 ; # xsd:int
         bsbm:productPropertyNumeric3 ?lit_propertyNum3 ; # xsd:int
         bsbm:productPropertyNumeric4 ?lit_propertyNum4 ; # xsd:int
         bsbm:productPropertyNumeric5 ?lit_propertyNum5 ; # xsd:int
         bsbm:productPropertyNumeric6 ?lit_propertyNum6 ; # xsd:int
         bsbm:productPropertyTextual1 ?lit_propertyTex1 ;
         bsbm:productPropertyTextual2 ?lit_propertyTex2 ;
         bsbm:productPropertyTextual3 ?lit_propertyTex3 ;
         bsbm:productPropertyTextual4 ?lit_propertyTex4 ;
         bsbm:productPropertyTextual5 ?lit_propertyTex5 ;
         bsbm:productPropertyTextual6 ?lit_propertyTex6 ;
         dc:publisher ?producer ;
         dc:date ?p_publishDate . # xsd:date;

?productfeature a bsbm:ProductFeature ;
                rdfs:label ?pf_label ;
                rdfs:comment ?pf_comment ;
	        dc:publisher ?prodPub ;
                dc:date ?pf_publishDate . # xsd:date

?producttype a bsbm:ProductType ;
             rdfs:label ?pt_label ;
             rdfs:comment ?pt_comment ;
             rdfs:subClassOf ?producttypeparent ;
	     dc:publisher ?pt_publisher ;
             dc:date ?pt_publishDate . # xsd:date

?review a bsbm:Review ;
        bsbm:reviewFor ?product ;
        rev:reviewer ?person ;
        bsbm:reviewDate ?lit_reviewDate ; # xsd:date
        dc:title ?lit_title ;
        rev:text ?lit_text ; # @review_lang 
        bsbm:rating1 ?lit_rating1 ; # xsd:int
        bsbm:rating2 ?lit_rating2 ; # xsd:int
        bsbm:rating3 ?lit_rating3 ; # xsd:int
        bsbm:rating4 ?lit_rating4 ; # xsd:int
	dc:publisher ?rev_publisher ;
        dc:date ?rev_publishDate . # xsd:date

?vendor a bsbm:Vendor ;
        rdfs:label ?vend_label ;
        rdfs:comment ?vend_comment ;
        foaf:homepage ?vend_homepage ;
	bsbm:country ?vend_country ;
	dc:publisher ?vend_publisher ;
        dc:date ?lit_publishDate . # xsd:date
} WHERE {
?offer
       offer:product ?product ;
       offer:vender ?vendor ;
       offer:price ?lit_price ;
       offer:validFrom ?lit_validFrom ;
       offer:validTo ?lit_validTo ;
       offer:deliveryDays ?lit_deliveryDays ;
       offer:offerWebpage ?lit_offerWebpage ;
       offer:vendor ?vendor ;
       offer:publisher ?offer_publisher ;
       offer:nr ?offer_nr ;
       offer:publishDate ?offer_publishDate .

?person # tr:bind(?person, bsbm-inst:, "dataFromRatingSite@@person.publisher@@/Reviewer@@person.nr@@")
        person:name ?lit_name ;
        person:mbox_sha1sum ?lit_mbox_sha1sum ;
        person:publishDate ?per_publishDate .
        # tr:bind(?perCountry, "http://downlode.org/rdf/iso-3166/countries#@@person:country@@")
        # tr:bind(?perPublisher, bsbm-inst:, "dataFromRatingSite@@person.publisher@@/RatingSite@@person.publisher@@")

?producer # tr:bind(?producer, bsbm-inst:, "dataFromProducer@@producer.nr@@/Producer@@producer.nr@@")
          producer:label ?prod_label ;
          producer:comment ?prod_comment ;
          producer:homepage ?prod_homepage ;
          # tr:bind(?prodCountry, "http://downlode.org/rdf/iso-3166/countries#@@producer.country@@")
          # tr:bind(?prodPublisher, bsbm-inst:, "dataFromProducer@@producer.nr@@/Producer@@producer.nr@@")
          producer:publishDate ?prod_publishDate .

?product # tr:bind(?product, bsbm-inst:, "dataFromProducer@@product.producer@@/Product@@product.nr@@")
         product:label ?p_label ;
         product:comment ?p_comment ;
         product:producer ?producer ;
         product:propertyNum1 ?lit_propertyNum1 ;
         product:propertyNum2 ?lit_propertyNum2 ;
         product:propertyNum3 ?lit_propertyNum3 ;
         product:propertyNum4 ?lit_propertyNum4 ;
         product:propertyNum5 ?lit_propertyNum5 ;
         product:propertyNum6 ?lit_propertyNum6 ;
         product:propertyTex1 ?lit_propertyTex1 ;
         product:propertyTex2 ?lit_propertyTex2 ;
         product:propertyTex3 ?lit_propertyTex3 ;
         product:propertyTex4 ?lit_propertyTex4 ;
         product:propertyTex5 ?lit_propertyTex5 ;
         product:propertyTex6 ?lit_propertyTex6 ;
         product:producer ?producer ;
         product:publishDate ?p_publishDate .

?pfp # tr:bind(?pfp, bsbm-inst:, "ProductFeature@@productfeatureproduct.productfeature@@")
     productfeatureproduct:product ?product .

?ptp # tr:bind(?ptp, bsbm-inst:, "ProductType@@producttypeproduct.producttype@@")
     producttypeproduct:product ?product .

?productfeature # tr:bind(?productfeature, bsbm-inst:, "ProductFeature@@productfeature.nr@@")
                productfeature:label ?pf_label ;
                productfeature:comment ?pf_comment ;
                # tr:bind(?prodPub, bsbm-inst:, "StandardizationInstitution@@productfeature.publisher@@")
                productfeature:publishDate ?pf_publishDate .

?producttype # tr:bind(?producttype, bsbm-inst:, "ProductType@@producttype.nr@@")
             producttype:label ?pt_label ;
             producttype:comment ?pt_comment ;
             producttype:parent ?producttypeparent ;
             # tr:bind(?pt_publisher, bsbm-inst:, "StandardizationInstitution@@producttype.publisher@@")
             producttype:publishDate ?pt_publishDate .

?review # tr:bind(?review, bsbm-inst:, "dataFromRatingSite@@review.publisher@@/Review@@review.nr@@")
        review:product ?product ;
        review:person ?person ;
        review:reviewDate ?lit_reviewDate ;
        review:title ?lit_title ;
        review:text ?lit_text ;
        review:language ?review_lang ; # en ja zh de fr es ru ko
        review:rating1 ?lit_rating1 ;
        review:rating2 ?lit_rating2 ;
        review:rating3 ?lit_rating3 ;
        review:rating4 ?lit_rating4 ;
        # tr:bind(?rev_publisher, bsbm-inst:, "dataFromRatingSite@@review.publisher@@/RatingSite@@review.publisher@@")
        review:publishDate ?rev_publishDate .

?vendor # tr:bind(?vendor, bsbm-inst:, "dataFromVendor@@vendor.nr@@/Vendor@@vendor.nr@@")
        vendor:label ?vend_label ;
        vendor:comment ?vend_comment ;
        vendor:homepage ?vend_homepage ;
        # tr:bind(?vend_country, "http://downlode.org/rdf/iso-3166/countries#@@vendor.country@@")
        # tr:bind(?vend_publisher, bsbm-inst:, "dataFromVendor@@vendor.nr@@/Vendor@@vendor.nr@@")
        vendor:publishDate ?lit_publishDate .
}

