# disj1
# from http://www.w3.org/2008/07/MappingRules/#disj1 Revision: 1.38 
# $Id: query_spec-disj1.rq,v 1.1 2008-09-08 13:12:41 eric Exp $

SELECT ?name
 WHERE { ?who emplP:lastName "Smith"
         { ?above   manageP:manages ?who .
           ?above   manageP:manager ?manager .
           ?manager emplP:lastName  ?name }
         UNION
         { ?below   manageP:manager ?who .
           ?below   manageP:manages ?managed .
           ?managed emplP:lastName  ?name } }
