# DiabeticPatientsDataSet to CPO

# common namespaces
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix log: <http://www.w3.org/2000/10/swap/log#>

# namespaces from the database's public projection
prefix hl7: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#hl7_>
prefix sdtm: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#sdtm_>

# namespaces from the database's default-mapping
prefix : <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#_>
prefix patient: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#patient_>
prefix sex: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#sex_>
prefix enterpriseEntry: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#enterpriseEntry_>
prefix definitionSet: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#definitionSet_>
prefix encounter: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#encounter_>
prefix referringProvider: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#referringProvider_>
prefix encounterType: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#encounterType_>
prefix provider2: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#provider2_>
prefix provider: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#provider_>
prefix itemMedication: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#itemMedication_>
prefix visit: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#visit_>
prefix iCD9Diagnosis: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#iCD9Diagnosis_>
prefix medication: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#medication_>
prefix routeOfAdmin: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#routeOfAdmin_>
prefix freqUnits: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#freqUnits_>
prefix formOfMedication: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#formOfMedication_>
prefix medDict: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#medDict_>
prefix prescribedBy: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#prescribedBy_>
prefix qo: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#qo_>
prefix activityHeader: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#activityHeader_>
prefix current: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#current_>
prefix itemTestReults: <http://www.w3.org/2008/04/DiabeticPatientsDataSet/ClinicalPracticeOntology-Version3.owl#itemTestReults_>

prefix patient: <http://someClinic.exampe/DB/Patient#>
prefix names: <http://someClinic.exampe/DB/Names#>
prefix bar: <http://someClinic.exampe/DB/bar#>
prefix baz: <http://someClinic.exampe/DB/baz#>


#@forAll .
#CONSTRUCT { ?x hl7:routeCode "oral" } WHERE { ?x :pRouteOfAdmin routeOfAdmin:15 }


# ?m =: medication:10150700017
# ?subject =:  patient:1505583
# ?route =: routeOfAdmin:15

#@forAll ?administration ?patient ?m ?dictEntry ?route ?drugName ?doseUnit ?doseQuantity .
CONSTRUCT {
  _:SUBaDM sdtm:subject ?PATIENT .
  ?PATIENT sdtm:foo ?FOOP . _:Z sdtm:fool ?FOOP .
} WHERE {
#Item_Medication.ttl:18:
    # add OPTIONALs to show a smaller stem query
  _:ADMINISTRATION patient:name _:PATIENT_name .
OPTIONAL{ _:HAS_attr1 baz:attr1 ?FOOP.}
  OPTIONAL {_:PATIENT_name names:patient ?PATIENT .
  ?PATIENT bar:attr2 ?FOOP .}OPTIONAL{ _:HAS_attr1 bar:attr3 ?FOOP.}
}
