PREFIX hl7: <http://www.hl7.org/v3ballot/xml/infrastructure/vocabulary/vocabulary#>

SELECT ?pat ?midName ?bd ?sex ?takes
WHERE
{
  ?pat hl7:entityName ?midName ;
       hl7:livingSubjectBirthTime ?bd ;
       hl7:administrativeGenderCodePrintName ?sex ;
       hl7:substanceAdministration [
      a hl7:SubstanceAdministration ;
      hl7:consumable [
          hl7:displayName ?takes ;
          hl7:activeIngredient [ hl7:classCode 6809 ]
      ] ;
      hl7:effectiveTime [ hl7:start ?indicDate ]
  ]
  FILTER ( ?bd > "1999-01-01T00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> )
  FILTER ( ?indicDate < "2010-01-01T00:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> )
}
