# query_leadTrailOpts — query to explore optional inclusions
# $Id: query_leadTrailOpts.rq,v 1.2 2008-09-22 08:33:46 eric Exp $

PREFIX iface: <http://iface.example/>
PREFIX stem: <http://stem.example/>

SELECT ?QleadOptIncl2 ?Qmand1 ?QtrailOptIncl2 WHERE {
  ?Qs iface:leadOptIncl2  ?QleadOptIncl2  .
  ?Qs iface:mand          ?Qmand1         .
  ?Qs iface:trailOptIncl2 ?QtrailOptIncl2 .
 }
