# ruleMap_leadTrailOpts — rule map to explore optional inclusions
# $Id: ruleMap_leadTrailOpts.rq,v 1.4 2008-09-27 15:18:15 eric Exp $

PREFIX iface: <http://iface.example/>
PREFIX table1: <http://stem.example/table1#>
PREFIX table2: <http://stem.example/table2#>

CONSTRUCT {
  ?s iface:leadOptIncl2  ?leadOptIncl2  .
  ?s iface:mand          ?mand1         .
  ?s iface:trailOptIncl2 ?trailOptIncl2 }
WHERE {
  OPTIONAL { ?s1            table1:leadOptExcl1  ?leadOptExcl1  .
             ?leadOptExcl1  table2:leadOptExcl2  ?leadOptExcl2  }
  OPTIONAL { ?s2            table1:leadOptNeed1  ?leadOptNeed1  .
             ?leadOptNeed1  table2:leadOptNeed2  ?leadOptNeed2  }
  OPTIONAL { ?s3            table1:leadOptIncl1  ?leadOptNeed1  .
             ?leadOptNeed1  table2:leadOptIncl2  ?leadOptIncl2  }
  ?s                        table1:mand          ?mand1
  OPTIONAL { ?s             table1:trailOptExcl1 ?trailOptExcl1 .
             ?trailOptExcl1 table2:trailOptExcl2 ?trailOptExcl2 }
  OPTIONAL { ?s             table1:trailOptNeed1 ?trailOptNeed1 .
             ?trailOptNeed1 table2:trailOptNeed2 ?trailOptNeed2 }
  OPTIONAL { ?s             table1:trailOptIncl1 ?trailOptNeed1 .
             ?trailOptNeed1 table2:trailOptIncl2 ?trailOptIncl2 }
}
