# q1-db.rq — DB-specific representation of BSBM query 1
# http://www4.wiwiss.fu-berlin.de/bizer/BerlinSPARQLBenchmark/spec/index.html#queryTripleQ1
# $Id: q1-db.rq,v 1.2 2008-12-29 23:12:37 eric Exp $

SELECT DISTINCT ?product ?label 
WHERE
{
#    ?product <http://bsbm.example/db/producer#label> ?label .
    ?product <http://bsbm.example/db/product#label> ?label .
    ?product <http://bsbm.example/db/product#propertyNum1> ?value1 .
    <http://bsbm.example/db/productfeatureproduct/productfeature.5> <http://bsbm.example/db/productfeatureproduct#product> ?product .
    <http://bsbm.example/db/productfeatureproduct/productfeature.7> <http://bsbm.example/db/productfeatureproduct#product> ?product .
    <http://bsbm.example/db/producttypeproduct/producttype.59> <http://bsbm.example/db/producttypeproduct#product> ?product .
#    ?product <http://bsbm.example/db/productfeature#label> ?label .
#    ?product <http://bsbm.example/db/producttype#label> ?label .
#    ?product <http://bsbm.example/db/vendor#label> ?label .
  FILTER ( ?value1 > 578 )
}
ORDER BY ?label
LIMIT 10
