*R =
| ?X | ?Y |
|  1 |  2 |.
*X =
+----+----+
| ?X | ?Z |
|  1 |  3 |
|  2 |  4 |
+----+----+
*M =
│ ?X │ ?Z │
│  1 │  3 │
│  2 │  4 │.
*S =
┌────┬────┐
│ ?X │ ?Z │
│  1 │  3 │
│  1 │  3 │
│  2 │  4 │
└────┴────┘
SELECT * {*S *S}