# prenormalize.rq - rules parsed from prenormalize.wsdl
# $Id$

PREFIX bas: <http://www.semanticbits.com/piq-workflow/wsdl/>
PREFIX prt: <http://www.semanticbits.com/piq-workflow/wsdl/partition>
PREFIX chk: <http://www.semanticbits.com/piq-workflow/wsdl/chunkisize>
PREFIX zpj: <http://www.semanticbits.com/piq-workflow/wsdl/zproject>
PREFIX prn: <http://www.semanticbits.com/piq-workflow/wsdl/prenormalize>
PREFIX nmz: <http://www.semanticbits.com/piq-workflow/wsdl/normalizeZ>
PREFIX aut: <http://www.semanticbits.com/piq-workflow/wsdl/autoalign>
PREFIX mst: <http://www.semanticbits.com/piq-workflow/wsdl/mst>
PREFIX stc: <http://www.semanticbits.com/piq-workflow/wsdl/stitch>
PREFIX reg: <http://www.semanticbits.com/piq-workflow/wsdl/reorganize>
PREFIX wrp: <http://www.semanticbits.com/piq-workflow/wsdl/warp>
PREFIX prp: <http://www.semanticbits.com/piq-workflow/wsdl/preprocess>

LABEL prt:opPartition		CONSTRUCT { ?a bas:has bas:DimFile				} WHERE { ?a bas:has bas:ImageFile							}
LABEL chk:opChunkisize		CONSTRUCT { ?b bas:has bas:ChucksizeMetaFile, bas:StackFile	} WHERE { ?b bas:has bas:DimFile							}
LABEL zpj:opZproject		CONSTRUCT { ?c bas:has bas:ProjectedChunkFile			} WHERE { ?c bas:has bas:ChucksizeMetaFile, bas:StackFile				}
LABEL prn:opPrenormalize	CONSTRUCT { ?d bas:has bas:OffsetTileFile, bas:AverageTileFile	} WHERE { ?d bas:has bas:ProjectedChunkFile						}
LABEL nmz:opNormalizeZ		CONSTRUCT { ?e bas:has bas:NormalizedProjectedChunkFile		} WHERE { ?e bas:has bas:ProjectedChunkFile, bas:OffsetTileFile, bas:AverageTileFile	}
LABEL aut:opAutoalign		CONSTRUCT { ?f bas:has bas:OffsetsFile				} WHERE { ?f bas:has bas:NormalizedProjectedChunkFile					}
LABEL mst:opMst			CONSTRUCT { ?g bas:has bas:DisplacementsFile			} WHERE { ?g bas:has bas:OffsetsFile							}
LABEL stc:opStitch		CONSTRUCT { ?h bas:has bas:StichedChunkFile			} WHERE { ?h bas:has bas:NormalizedProjectedChunkFile, bas:DisplacementsFile		}
LABEL reg:opReorganize		CONSTRUCT { ?i bas:has bas:StichedChunkFile			} WHERE { ?i bas:has bas:StichedChunkFile						}
LABEL wrp:opWarp		CONSTRUCT { ?j bas:has bas:WarpMetaFile				} WHERE { ?j bas:has bas:ControlPointsFile, bas:StichedChunkFile			}
LABEL prp:opPreprocess		CONSTRUCT { ?k bas:has bas:PreprocessMetaFile			} WHERE { ?k bas:has bas:WarpMetaFile							}

