# prenormalize.rq - rules parsed from prenormalize.wsdl
# $Id$

PREFIX bas: <http://www.semanticbits.com/piq-workflow/wsdl/>
PREFIX tns: <http://www.semanticbits.com/piq-workflow/wsdl/prenormalize>

LABEL tns:opPrenormalize
CONSTRUCT { ?d bas:has bas:OffsetTileFile, bas:AverageTileFile }
    WHERE { ?d bas:has bas:ProjectedChunkFile }
