<?xml version="1.0" encoding="utf-8" ?> 
<definitions 
	xmlns="http://schemas.xmlsoap.org/wsdl/"
 	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
 	xmlns:xs="http://www.w3.org/2001/XMLSchema"
 	xmlns:bas="http://www.semanticbits.com/piq-workflow/wsdl/"
 	xmlns:tns="http://www.semanticbits.com/piq-workflow/wsdl/reorganize"
 	xmlns:spat="http://dev.w3.org/cvsweb/perl/modules/W3C/SPDL/"
 	targetNamespace= "http://www.semanticbits.com/piq-workflow/wsdl/reorganize">

 <documentation>
	 This document describes a mock service corresponding to the 'reorganize'
	 node from the PIQ Workflow in Fig 4a of "Parameterized specification,
	 configuration and execution of data-intensive scientific workflows" by
	 Kumar et al.  The reorganize node takes as input a StitchedChunkFile and returns a StitchedChunkFile.
</documentation>



<types>
	<xs:schema
		targetNamespace="http://www.semanticbits.com/piq-workflow/wsdl/reorganize"
     	xmlns:xs="http://www.w3.org/2001/XMLSchema"
     	xmlns:tns="http://www.semanticbits.com/piq-workflow/wsdl/reorganize">
	  <xs:element name="StitchedChunkFile" type="xs:string"/>   
	 
	</xs:schema>    
</types>


<message name="InputMessage">
    <part name="body" element="tns:StitchedChunkFile"/>
</message>

<message name="OutputMessage">
    <part name="body" element="tns:StitchedChunkFile"/>
</message>


<portType name="reorganizePortType">
    <operation name="opReorganize">
      <input message="tns:InputMessage" spat:SPAT="?reorganize bas:has bas:StichedChunkFile"/>
      <output message="tns:OutputMessage" spat:SPAT="?reorganize bas:has bas:StichedChunkFile"/>
    </operation>
</portType>


 <binding name="reorganizeSOAPBinding" type="tns:reorganizePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="opReorganize">
    <soap:operation soapAction="http://www.semanticbits.com/piq-workflow/reorganize"/>
      <input>
	<soap:body use="literal"/>
      </input>
      <output>
	<soap:body use="literal"/>
      </output>
    </operation>
  </binding>


<!-- This is mock-up of a service: there is no endpoint associated. - SH -->
<service name="reorganizeService">
    <port name="reorganizeServicePort" binding="tns:reorganizeSOAPBinding">
      <soap:address location="http://www.semanticbits.com/piq-workflow/reorganize"/>
    </port>
  </service>



</definitions>

