PREFIX encounter: <http://informatics.kumc.edu/encounter/>
PREFIX testtype: <http://informatics.kumc.edu/testtype/>

SELECT ?pat ?test ?encDate 
WHERE
{
  SELECT (encounter:_123 AS ?encounter)
         (CONCAT(testtype:, ?_all_0_concept_cd) AS ?test) 
  WHERE
  {
    ?_all_0_concept <http://informatics.kumc.edu/404/i2b2demo/concept_dimension#concept_cd> ?_all_0_concept_cd .
    ?_all_0_concept <http://informatics.kumc.edu/404/i2b2demo/concept_dimension#concept_path> ?_all_0_concept_path .
    ?_all_0_entry <http://informatics.kumc.edu/404/i2b2demo/observation_fact#concept_cd> ?_all_0_concept_cd .
    ?_all_0_entry <http://informatics.kumc.edu/404/i2b2demo/observation_fact#encounter_num> "_123"  .
    ?_all_0_entry <http://informatics.kumc.edu/404/i2b2demo/observation_fact#patient_num> ?pat .
    ?_all_0_entry <http://informatics.kumc.edu/404/i2b2demo/observation_fact#start_date> ?encDate .
  }
}
LIMIT 10
