# ext_select_expr-01 - SELECT expression with no alias

# $Id$

SELECT ?bPlusC SUM(?bPlusC) (1 - COUNT(*) AS ?oneMinusCount)
{
    {
      SELECT * {}
      BINDINGS
?a ?b  ?c {
(1 10 2)
(1  9 3)
(1 11 4)
          }
    }
}
GROUP BY (?a AS ?x) ((?b+?c) AS ?bPlusC)
  HAVING (?bPlusC < 13)

