/* ShExCScanner.hpp - hand-written wrapper around the flex-generated
 * ShExFlexLexer, providing token construction helpers for the ShEx2 scanner.
 */

#ifndef ShExScanner_H
#define ShExScanner_H

// Flex expects the signature of yylex to be defined in the macro YY_DECL, and
// the C++ parser expects it to be declared. We can factor both as follows.

#ifndef YY_DECL

#define	YY_DECL						\
    w3c_sw::ShExParser::token_type				\
    w3c_sw::ShExScanner::lex(				\
	w3c_sw::ShExParser::semantic_type* yylval,		\
	w3c_sw::ShExParser::location_type* yylloc		\
    )
#endif

#ifndef __FLEX_LEXER_H
#define yyFlexLexer ShExFlexLexer
#include "FlexLexer.h"
#undef yyFlexLexer
#endif

#include "ShExCParser.hpp"

namespace w3c_sw {

/** ShExScanner is a derived class to add some extra function to the scanner
 * class. Flex itself creates a class named yyFlexLexer, which is renamed using
 * macros to ShExFlexLexer. However we change the context of the generated
 * yylex() function to be contained within the ShExScanner class. This is required
 * because the yylex() defined in ShExFlexLexer has no parameters. */
class ShExScanner : public ShExFlexLexer
{
protected:
    ShExDriver* driver;

public:
    /** Create a new scanner object. The streams arg_yyin and arg_yyout default
     * to cin and cout, but that assignment is only made when initializing in
     * yylex(). */
    ShExScanner (ShExDriver* driver, std::istream* in = NULL, std::ostream* out = NULL)
	: ShExFlexLexer(in, out), driver(driver)
    {  }

    /** Required for virtual functions */
    virtual ~ShExScanner () {  }

    /** This is the main lexing function. It is generated by flex according to
     * the macro declaration YY_DECL above. The generated bison parser then
     * calls this virtual function to fetch new tokens. */
    virtual ShExParser::token_type lex(
	ShExParser::semantic_type* yylval,
	ShExParser::location_type* yylloc
	);
    ShExParser::token_type lexWrapper(
	   ShExParser::semantic_type* yylval,
	   ShExParser::location_type* yylloc
					   ) {
	try {
	    return lex(yylval, yylloc);
	} catch (const char* e) {
	    std::stringstream s;
	    s << *yylloc << ": " << e;
	    throw s.str();
	}
    }

    /** Enable debug output (via arg_yyout) if compiled into the scanner. */
    void set_debug (bool b) {
	yy_flex_debug = b;
    }

protected:
    ShExParser::token_type typedLiteral (ShExParser::semantic_type*& yylval, ShExParser::token_type tok) {
	std::istringstream is(yytext);

	switch (tok) {
	case w3c_sw::ShExParser::token::INTEGER:
	    int i;
	    is >> i;
	    yylval->p_Literal = driver->getNumericRDFLiteral(yytext, i);
	    return tok;
	case w3c_sw::ShExParser::token::DECIMAL:
	    float f;
	    is >> f;
	    yylval->p_Literal = driver->getNumericRDFLiteral(yytext, f);
	    return tok;
	case w3c_sw::ShExParser::token::DOUBLE:
	    double d;
	    is >> d;
	    yylval->p_Literal = driver->getNumericRDFLiteral(yytext, d);
	    return tok;
	default: throw(new std::exception());
	}
    }

    ShExParser::token_type unescapeString (ShExParser::semantic_type*& yylval, ShExParser::location_type* yylloc, const char* text, size_t len, ShExParser::token_type tok) {
	std::string* space = new std::string;
	YaccDriver::unescapeString(text, len, space, yylloc);
	yylval->p_string = space;
	return tok;
    }

    /** A LANG_STRING_LITERAL* token: <quote>body<quote>@tag . The tag is the
     * suffix after the last '@'; it contains only [A-Za-z0-9-]. */
    ShExParser::token_type langString (ShExParser::semantic_type*& yylval,
				       ShExParser::location_type* yylloc,
				       size_t trim, ShExParser::token_type tok) {
	size_t at = yyleng;
	while (at > 0 && yytext[at-1] != '@')
	    --at;
	std::string tag(yytext + at, yyleng - at);
	std::string body;
	YaccDriver::unescapeString(yytext + trim, at - 1 - 2*trim, &body, yylloc);
	yylval->p_Literal = driver->getRDFLiteral(body, NULL, new LANGTAG(tag));
	return tok;
    }

    /** REPEAT_RANGE: {m} {m,} {m,n} {m,*} */
    ShEx::CardPOD repeatRange (const char* text, size_t len) {
	ShEx::CardPOD card;
	std::string inner(text + 1, len - 2);
	size_t comma = inner.find(',');
	card.min = atoi(inner.c_str());
	if (comma == std::string::npos)
	    card.max = card.min;
	else {
	    std::string maxStr = inner.substr(comma + 1);
	    if (maxStr.empty() || maxStr == "*")
		card.max = ShEx::Unbounded;
	    else
		card.max = atoi(maxStr.c_str());
	}
	return card;
    }

    /** REGEXP: /pattern/flags with ShExC regex escaping. Regex metacharacter
     * escapes stay escaped, \\t \\n \\r become control characters, \\uXXXX and
     * \\UXXXXXXXX become the code point, and "\\/" becomes "/". */
    ShEx::PatternC* regexPattern (const char* text, size_t len,
				  ShExParser::location_type* yylloc) {
	size_t end = len;
	while (end > 0 && text[end-1] != '/')
	    --end;
	std::string flags(text + end, len - end);
	std::string pattern;
	for (size_t i = 1; i + 1 < end; ++i) {
	    char c = text[i];
	    if (c != '\\') {
		pattern += c;
		continue;
	    }
	    char e = text[++i];
	    switch (e) {
	    case 't': pattern += "\\t"; break;
	    case 'n': pattern += "\\n"; break;
	    case 'r': pattern += "\\r"; break;
	    case '/': pattern += '/'; break;
	    case '.': case '\\': case '?': case '*': case '+':
	    case '{': case '}': case '(': case ')': case '|':
	    case '^': case '$': case '[': case ']': case '-':
		pattern += '\\';
		pattern += e;
		break;
	    case 'u': case 'U': {
		std::string space;
		size_t width = e == 'u' ? 4 : 8;
		YaccDriver::unescapeNumeric(text + i - 1, width + 2, &space, yylloc);
		pattern += space;
		i += width;
		break;
	    }
	    default:
		driver->error(*yylloc, std::string("unexpected escape \\") + e + " in regular expression");
	    }
	}
	return new ShEx::PatternC(pattern, flags);
    }

    /** CODE: "{" body "%}" with \\% and \\\\ escapes plus UCHARs. Counts the
     * newlines the token spans. */
    std::string* semActCode (const char* text, size_t len,
			     ShExParser::location_type* yylloc) {
	std::string* code = new std::string();
	for (size_t i = 1; i + 2 < len; ++i) {
	    char c = text[i];
	    if (c == '\n')
		yylloc->end.lines(1);
	    if (c != '\\') {
		*code += c;
		continue;
	    }
	    char e = text[++i];
	    switch (e) {
	    case '%': *code += '%'; break;
	    case '\\': *code += '\\'; break;
	    case 'u': case 'U': {
		std::string space;
		size_t width = e == 'u' ? 4 : 8;
		YaccDriver::unescapeNumeric(text + i - 1, width + 2, &space, yylloc);
		*code += space;
		i += width;
		break;
	    }
	    default:
		driver->error(*yylloc, std::string("unexpected escape \\") + e + " in semantic action");
	    }
	}
	return code;
    }

    /** resolvePrefix
     * Assumes barewords are localnames in the default namespace.
     * This leaves it to the lexer to warn about missing prefixes.
     */
    template <typename T> // e.g. ShExParser::location_type
    const URI* resolvePrefix (const char* yytext, T* yylloc) {
	std::string stripped;
	YaccDriver::unescapeReserved(yytext, ::strlen(yytext), &stripped, yylloc);

	size_t index = stripped.find(':');
	if (index == std::string::npos)
	    index = 0;
	std::string prefix = stripped.substr(0, index);
	const URI* nspace = driver->getNamespace(prefix, true);
	if (nspace == NULL)
	    nspace = driver->prefixError(prefix, *yylloc);
	stripped.replace(0, index+1, nspace->getLexicalValue());

	return driver->getAbsoluteURI(stripped.c_str());
    }

    template <typename T> // e.g. ShExParser::location_type
    const URI* unescapeAndResolveBase (const char* p_rel, size_t len, T* yylloc) {
	std::string stripped;
	try {
	    YaccDriver::unescapeNumeric(p_rel, len, &stripped, yylloc,
					AtomFactory::validate & AtomFactory::VALIDATE_IRIcharacters
					? &CharacterRange::NonIRI
					: NULL);
	} catch (std::runtime_error& e) {
	    driver->error(*yylloc, e.what());
	}
	try {
	    return driver->getAbsoluteURI(stripped.c_str());
	} catch (std::runtime_error& e) {
	    driver->error(*yylloc, e.what());

	    // We're here because we've noted this error and are
	    // continuing. We turn off validation so we can get this
	    // IRI from the AtomFactory and then restore the original
	    // state.
	    disableValidation();
	    const URI* ret = driver->getAbsoluteURI(stripped.c_str());
	    restoreValidation();
	    return ret;
	}
    }

    template <typename T> // e.g. ShExParser::location_type
    void scanError (const char* msg, char quote, T* yylloc) {
	std::stringstream ss;
	ss << "Malformed " << msg << " " << quote << yytext << quote;
	driver->error(*yylloc, ss.str());
    }

    AtomFactory::e_Validation validation;
    void disableValidation () {
	validation = AtomFactory::validate;
	AtomFactory::validate = static_cast<AtomFactory::e_Validation>
	    // enums become ints when you & them so cast back to enum.
	    (AtomFactory::validate&~AtomFactory::VALIDATE_IRIcharacters);
    }
    void restoreValidation () {
	    AtomFactory::validate = validation;
    }

};

} // namespace w3c_sw

#endif // ShExScanner_H
