// $Id: SPARQLScanner.hpp,v 1.3 2008-10-03 07:06:02 eric Exp $

#ifndef SPARQLScanner_H
#define SPARQLScanner_H

// Flex expects the signature of yylex to be defined in the macro YY_DECL, and
// the C++ parser expects it to be declared. We can factor both as follows.

#ifndef YY_DECL

#define	YY_DECL						\
    w3c_sw::SPARQLParser::token_type				\
    w3c_sw::SPARQLScanner::lex(				\
	w3c_sw::SPARQLParser::semantic_type* yylval,		\
	w3c_sw::SPARQLParser::location_type* yylloc		\
    )
#endif

#ifndef __FLEX_LEXER_H
#define yyFlexLexer SPARQLFlexLexer
#include "FlexLexer.h"
#undef yyFlexLexer
#endif

#include "SPARQLParser.hpp"

namespace w3c_sw {

/** SPARQLScanner is a derived class to add some extra function to the scanner
 * class. Flex itself creates a class named yyFlexLexer, which is renamed using
 * macros to SPARQLFlexLexer. However we change the context of the generated
 * yylex() function to be contained within the SPARQLScanner class. This is required
 * because the yylex() defined in SPARQLFlexLexer has no parameters. */
class SPARQLScanner : public SPARQLFlexLexer
{
private:
    SPARQLDriver* driver;
public:
    /** Create a new scanner object. The streams arg_yyin and arg_yyout default
     * to cin and cout, but that assignment is only made when initializing in
     * yylex(). */
    SPARQLScanner(SPARQLDriver* driver, std::istream* arg_yyin = 0,
	    std::ostream* arg_yyout = 0);

    /** Required for virtual functions */
    virtual ~SPARQLScanner();

    /** This is the main lexing function. It is generated by flex according to
     * the macro declaration YY_DECL above. The generated bison parser then
     * calls this virtual function to fetch new tokens. */
    virtual SPARQLParser::token_type lex(
	SPARQLParser::semantic_type* yylval,
	SPARQLParser::location_type* yylloc
	);
    SPARQLParser::token_type lexWrapper(
	   SPARQLParser::semantic_type* yylval,
	   SPARQLParser::location_type* yylloc
					   ) {
	try {
	    return lex(yylval, yylloc);
	} catch (const char* e) {
	    std::stringstream s;
	    s << *yylloc << ": " << e;
	    throw s.str();
	}
    }

    /** Enable debug output (via arg_yyout) if compiled into the scanner. */
    void set_debug(bool b);

    SPARQLParser::token_type typedLiteral(SPARQLParser::semantic_type*&, SPARQLParser::token_type tok);
    SPARQLParser::token_type unescape(SPARQLParser::semantic_type*&, SPARQLParser::location_type*&, size_t skip, SPARQLParser::token_type tok);

    /** resolvePrefix
     * Assumes barewords are localnames in the default namespace.
     * This leaves it to the lexer to warn about missing prefixes.
     */
    const URI* resolvePrefix (const char* yytext, SPARQLParser::location_type* yylloc) {
	std::string stripped;
	YaccDriver::unescapeReserved(yytext, ::strlen(yytext), &stripped, yylloc);

	size_t index = stripped.find(':');
	if (index == std::string::npos)
	    // throw(std::runtime_error("Inexplicable lack of ':' in prefix"));
	    index = 0;
	std::string prefix = stripped.substr(0, index);
	const URI* nspace = driver->getNamespace(prefix, true);
	if (nspace == NULL)
	    nspace = driver->prefixError(prefix, *yylloc);
	stripped.replace(0, index+1, nspace->getLexicalValue());

	return driver->getAbsoluteURI(stripped.c_str());
    }

    const URI* unescapeAndResolveBase (const char* p_rel, size_t len, SPARQLParser::location_type* yylloc) {
	std::string stripped;
	YaccDriver::unescapeNumeric(p_rel, len, &stripped, yylloc,
				    AtomFactory::validate & AtomFactory::VALIDATE_IRIcharacters
				    ? &CharacterRange::NonIRI
				    : NULL);
	return driver->getAbsoluteURI(stripped.c_str());
    }


};

} // namespace w3c_sw

#endif // SPARQLScanner_H
