#line 2 "lib/SQLScanner.cpp"

#line 4 "lib/SQLScanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer SQLFlexLexer
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
/* %endif */

/* %if-c++-only */
	std::istream* yy_input_file;
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */
/* %if-not-reentrant */
/* %not-for-header */

/* %ok-for-header */

/* %endif */
/* %endif */

void *SQLalloc (yy_size_t  );
void *SQLrealloc (void *,yy_size_t  );
void SQLfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

#define yytext_ptr yytext

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }

/* %if-c-only Standard (non-C++) definition */
/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[315] =
    {   0,
        0,    0,   66,   64,    2,    1,    1,   46,   64,   64,
        6,    7,   24,   43,    8,   44,   26,   45,   51,    3,
       36,   34,   37,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,    2,    1,   35,    0,   61,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   60,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   54,    0,   57,   52,   52,   51,    0,   38,
       39,   50,   50,   25,   50,   50,   50,   50,   50,   50,
       50,   40,   50,   50,   50,   50,   50,   50,   50,   30,

       32,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   61,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   60,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   55,   55,    0,   58,   58,    0,    0,
       52,    0,    0,   53,   33,   50,   50,   50,   50,   50,
       50,   50,   13,   50,   10,   50,   50,   42,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   55,    0,    0,   56,    0,
       58,    0,    0,   59,    0,   53,    0,   53,   50,   50,
       15,   50,   50,   21,   50,   31,   28,   50,   41,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   48,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   56,    0,   56,    0,   59,    0,   59,   50,   50,
       50,   50,   50,   27,   22,   50,   29,   50,   50,   50,
       50,    5,   19,   20,   49,   63,    0,    0,    0,    0,
       62,    0,    0,    0,    0,   47,    4,   50,   14,   50,

       23,   50,   50,   18,   17,   50,    9,   12,   50,   16,
       50,   50,   11,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   17,   18,
       19,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   37,   42,   37,   43,   37,
        1,   44,   45,    1,   37,    1,   46,   47,   23,   24,

       48,   49,   27,   28,   29,   30,   31,   50,   33,   51,
       35,   36,   37,   52,   53,   54,   55,   37,   42,   37,
       43,   37,    1,    1,    1,    1,    1,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   57,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   60,
       61,   62,   62,   63,   63,   63,   63,   63,   63,   63,

       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   64,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   66,   67,   67,   68,
       69,   69,   69,   70,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62
    } ;

static yyconst flex_int32_t yy_meta[71] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    4,    1,    4,    4,    4,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[320] =
    {   0,
        0,    0, 1002, 1198,  999, 1198,  997,  980,   65,  129,
     1198, 1198, 1198,   58, 1198,   59,  982, 1198,   62, 1198,
      978, 1198,  977,   43,    0,   45,   58,   46,   52,  949,
       60,   63,   60,  111,   61,   64,   99,   79,   56,  954,
      105,   96,  979, 1198, 1198,  194,  971,  158,  111,   62,
      118,   95,  124,  131,  157,  161,  167,  920,  258,  968,
      223,  175,  183,  187,  193,  222,  228,  231,  235,  247,
      918,  957,  284,  954,  285,   98,  295,  315,  190, 1198,
     1198,    0,  945,    0,   93,  113,   62,  117,  198,  933,
      296,    0,  938,  922,  286,  931,  294,  109,  288,    0,

        0,  298,  933,  290,  309,  304,  322,  890,  320,  865,
      850, 1198,  364,  315,  859,  321,  327,  333,  339,  345,
      353,  359, 1198,  428,  380,  810,  386,  392,  398,  404,
      410,  417,  423,  474,  484,  255,  485,  486,  338,  342,
      487,  349,  837,  836,    0,  828,  467,  479,  483,  481,
      756,  483,    0,  157,    0,  467,  759,    0,  314,  475,
      490,  754,  491,  492,  755,  486,  748,  485,  729,  707,
      535,  600,  513,  486,  491,  495,  363,  512,  468,  524,
      516,  530,  694,  665,  551,  557,  563,  729,  793,  587,
      569,  589,  593,  599,  616,  622,  625,  629,  635,  691,

      857,  641,  647,  654,  550,  700,  619,  701,  639,  707,
      721,  708,  627,  624,  617,  581,  543,  542,  616,  602,
      687,  706,  458,    0,  701,    0,    0,  700,    0,  717,
      705,  724,  706,  463,  222,  724,  544,  726,  378,    0,
      922,  703,  362,  719,  745,  751,  757,  763,  769,  775,
      986,  782,  322,  788,  809,  815,  821,  827,  833,  839,
      350,  345,  341,  302,  301,  297,  281,  260,  712,  743,
      240,  881,  222,    0,    0,  727,    0,  733,  882,  862,
      210,    0,    0,    0,    0, 1198, 1051,  852,  875,  881,
     1198, 1115,  887,  893,  899,    0,    0,  178,    0,  927,

        0,  161,  929,    0,    0,  946,    0,    0,  127,    0,
      947,  864,    0, 1198, 1185, 1188,  103, 1191, 1194
    } ;

static yyconst flex_int16_t yy_def[320] =
    {   0,
      314,    1,  314,  314,  314,  314,  314,  314,  315,  316,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  314,  314,  314,  315,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  316,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,

      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  314,  318,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  319,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      318,  318,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  315,  314,  314,  314,  319,  319,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,

      316,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      318,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      319,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  317,  317,
      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,  317,  317,  314,  318,  314,  314,  314,
      314,  319,  314,  314,  314,  317,  317,  317,  317,  317,

      317,  317,  317,  317,  317,  317,  317,  317,  317,  317,
      317,  317,  317,    0,  314,  314,  314,  314,  314
    } ;

static yyconst flex_int16_t yy_nxt[1269] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   25,   28,   25,   25,   29,   30,
       31,   32,   25,   33,   34,   35,   25,   36,   37,   38,
       39,   40,   25,    4,    4,   24,   25,   25,   41,   32,
       33,   36,   37,   42,   39,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
       47,   72,   74,   73,   75,   77,   83,   78,   87,   85,
       89,   84,   86,   90,   94,   91,   79,   95,  104,  108,
       92,   96,   88,   83,   97,   84,   86,   90,  103,  107,

       98,  148,   91,   87,   92,   82,  108,   94,   48,   79,
       95,  104,  103,   76,   98,  148,  107,  115,  115,  115,
      115,   49,  140,  105,  107,   50,  146,   51,   52,   53,
       54,   55,   56,   57,   58,   60,   99,  147,  106,   89,
      159,  107,   90,  146,  100,  140,  105,  111,  101,  311,
      110,  102,  106,  116,  116,  116,   90,  149,  159,   99,
      147,  100,  101,   46,   46,  102,  114,  114,  114,  114,
      114,  149,   61,   46,   46,   46,   46,   46,   46,  117,
      117,  117,  117,  117,  117,   62,  118,  118,  118,   63,
      226,   64,   65,   66,   67,   68,   69,   70,   71,  112,

      143,   46,  143,  308,   46,  144,   46,  226,   46,   46,
      306,   46,  119,  119,  119,  119,  119,  119,  120,  120,
      120,  120,  121,  121,  121,  121,  121,  121,   59,   59,
      125,  125,  125,  125,  125,  150,  305,   48,  126,  126,
      126,  126,   59,   59,   59,   59,   59,   59,  300,  150,
       49,  127,  127,  127,   50,  281,   51,   52,   53,   54,
       55,   56,   57,   58,  123,  208,   59,  208,  298,   59,
      209,   59,  281,   59,   59,  268,   59,  128,  128,  128,
      128,  128,  128,  129,  129,  129,  130,  130,  130,  130,
      130,  130,  131,  131,  131,  131,  268,  135,  138,   73,

       75,   61,  132,  132,  132,  132,  132,  132,  136,  139,
      141,  156,  266,  160,   62,  163,  266,  264,   63,  142,
       64,   65,   66,   67,   68,   69,   70,   71,   77,  152,
       78,  136,  139,  158,  156,  153,  160,  161,  163,   79,
      164,  165,  142,  166,  168,  229,  152,  158,  213,  153,
      213,  161,  215,  214,  215,  165,  264,  216,  164,  217,
      262,  217,   79,  229,  218,  262,  188,  168,  166,  172,
      115,  115,  115,  115,  115,  115,   46,   46,   46,   46,
       46,   46,  184,  184,  184,  184,  184,  184,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,

      185,  185,  185,  185,  185,  185,  171,  173,  186,  186,
      186,  186,  186,  186,  187,  187,  187,  187,  187,  187,
      174,  244,  244,  244,  175,  285,  176,  177,  178,  179,
      180,  181,  182,  183,  189,  126,  126,  126,  126,  126,
      126,   59,   59,   59,   59,   59,   59,  201,  201,  201,
      201,  201,  201,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,  202,  202,  202,  202,  202,
      202,  190,  203,  203,  203,  203,  203,  203,  204,  204,
      204,  204,  204,  204,  191,  280,  273,  220,  192,  134,
      193,  194,  195,  196,  197,  198,  199,  200,  205,  206,

      137,  211,  141,  221,  222,  223,  227,  225,  207,  210,
      212,  142,  220,  230,  231,  233,  234,  236,  171,  171,
      227,  205,  238,  246,  246,  246,  221,  230,  223,  222,
      225,  207,  210,  212,  142,  236,  238,  231,  233,  234,
      172,  242,  242,  242,  242,  242,  243,  243,  243,  243,
      171,  171,  171,  171,  171,  171,  171,  218,  218,  171,
      261,  171,  261,  171,  171,  262,  171,  245,  245,  245,
      245,  245,  245,  248,  248,  248,  248,  283,  173,  247,
      247,  247,  247,  247,  247,  249,  249,  249,  249,  249,
      249,  174,  188,  188,  283,  175,  216,  176,  177,  178,

      179,  180,  181,  182,  183,  241,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,  115,  115,
      115,  115,  115,  115,  252,  252,  252,  252,  252,  263,
      188,  263,  216,  188,  264,  188,  269,  188,  188,  214,
      188,  270,  214,  173,  253,  253,  253,  253,  188,  188,
      188,  188,  188,  188,  209,  270,  174,  254,  254,  254,
      175,  269,  176,  177,  178,  179,  180,  181,  182,  183,
      112,  255,  255,  255,  255,  255,  255,  256,  256,  256,
      257,  257,  257,  257,  257,  257,  258,  258,  258,  258,
      259,  259,  259,  259,  259,  259,   59,   59,   59,   59,

       59,   59,   59,   59,   59,   59,   59,   59,   48,  126,
      126,  126,  126,  126,  126,  206,  209,  265,  267,  265,
      267,   49,  266,  268,  207,   50,  271,   51,   52,   53,
       54,   55,   56,   57,   58,  189,  211,  272,  274,  275,
      271,  276,  277,  279,  278,  212,  260,  207,  282,  250,
      284,  296,  274,  275,  240,  272,  277,  279,  243,  243,
      243,  243,  243,  243,  276,  296,  301,  297,  212,  278,
      302,  282,  190,  284,  171,  171,  171,  171,  171,  171,
      301,  239,  237,  235,  302,  191,  232,  228,  224,  192,
      297,  193,  194,  195,  196,  197,  198,  199,  200,  251,

      287,  287,  287,  287,  287,  287,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  288,  288,
      288,  288,  288,  288,  289,  289,  289,  289,  289,  289,
      290,  290,  290,  290,  290,  290,  190,  253,  253,  253,
      253,  253,  253,  188,  188,  188,  188,  188,  188,  191,
      219,  144,  144,  192,   59,  193,  194,  195,  196,  197,
      198,  199,  200,  123,  292,  292,  292,  292,  292,  292,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  293,  293,  293,  293,  293,  293,  294,  294,
      294,  294,  294,  294,  295,  295,  295,  295,  295,  295,

       61,  304,  313,   46,  170,  299,  303,  171,  171,  171,
      171,  171,  171,   62,  169,  304,  313,   63,  167,   64,
       65,   66,   67,   68,   69,   70,   71,  286,  299,  303,
      171,  171,  171,  171,  171,  171,  243,  243,  243,  243,
      243,  243,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  253,  253,  253,  253,  253,  253,
      307,  162,  309,  157,  155,  173,  154,  151,  145,  137,
      310,  312,  134,  133,  124,  122,  113,  307,  174,  309,
       43,  109,  175,   93,  176,  177,  178,  179,  180,  181,
      182,  183,  291,  310,  312,   81,   80,   76,   45,   44,

       43,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  190,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  191,  314,  314,  314,  192,  314,  193,  194,
      195,  196,  197,  198,  199,  200,  172,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  173,  314,  314,  314,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  174,  314,  314,
      314,  175,  314,  176,  177,  178,  179,  180,  181,  182,
      183,  189,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  190,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  191,  314,  314,  314,  192,  314,  193,  194,  195,
      196,  197,  198,  199,  200,   46,  314,   46,   59,  314,
       59,  171,  171,  171,  188,  188,  188,    3,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314
    } ;

static yyconst flex_int16_t yy_chk[1269] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        9,   14,   16,   14,   16,   19,   24,   19,   27,   26,
       28,   24,   26,   28,   31,   29,   19,   32,   36,   39,
       29,   32,   27,   24,   33,   24,   26,   28,   35,   38,

       33,   87,   29,   27,   29,  317,   39,   31,    9,   19,
       32,   36,   35,   76,   33,   87,   42,   50,   50,   50,
       50,    9,   76,   37,   38,    9,   85,    9,    9,    9,
        9,    9,    9,    9,    9,   10,   34,   86,   37,   41,
       98,   42,   41,   85,   34,   76,   37,   42,   34,  309,
       41,   34,   37,   52,   52,   52,   41,   88,   98,   34,
       86,   34,   34,   48,   48,   34,   49,   49,   49,   49,
       49,   88,   10,   51,   51,   51,   51,   51,   51,   53,
       53,   53,   53,   53,   53,   10,   54,   54,   54,   10,
      154,   10,   10,   10,   10,   10,   10,   10,   10,   46,

       79,   48,   79,  302,   48,   79,   48,  154,   48,   48,
      298,   48,   55,   55,   55,   55,   55,   55,   56,   56,
       56,   56,   57,   57,   57,   57,   57,   57,   61,   61,
       62,   62,   62,   62,   62,   89,  281,   46,   63,   63,
       63,   63,   64,   64,   64,   64,   64,   64,  273,   89,
       46,   65,   65,   65,   46,  235,   46,   46,   46,   46,
       46,   46,   46,   46,   59,  136,   61,  136,  271,   61,
      136,   61,  235,   61,   61,  268,   61,   66,   66,   66,
       66,   66,   66,   67,   67,   67,   68,   68,   68,   68,
       68,   68,   69,   69,   69,   69,  267,   73,   75,   73,

       75,   59,   70,   70,   70,   70,   70,   70,   73,   75,
       77,   95,  266,   99,   59,  104,  265,  264,   59,   77,
       59,   59,   59,   59,   59,   59,   59,   59,   78,   91,
       78,   73,   75,   97,   95,   91,   99,  102,  104,   78,
      105,  106,   77,  107,  109,  159,   91,   97,  139,   91,
      139,  102,  140,  139,  140,  106,  263,  140,  105,  142,
      262,  142,   78,  159,  142,  261,  253,  109,  107,  113,
      114,  114,  114,  114,  114,  114,  116,  116,  116,  116,
      116,  116,  117,  117,  117,  117,  117,  117,  118,  118,
      118,  118,  118,  118,  119,  119,  119,  119,  119,  119,

      120,  120,  120,  120,  120,  120,  243,  113,  121,  121,
      121,  121,  121,  121,  122,  122,  122,  122,  122,  122,
      113,  177,  177,  177,  113,  239,  113,  113,  113,  113,
      113,  113,  113,  113,  124,  125,  125,  125,  125,  125,
      125,  127,  127,  127,  127,  127,  127,  128,  128,  128,
      128,  128,  128,  129,  129,  129,  129,  129,  129,  130,
      130,  130,  130,  130,  130,  131,  131,  131,  131,  131,
      131,  124,  132,  132,  132,  132,  132,  132,  133,  133,
      133,  133,  133,  133,  124,  234,  223,  147,  124,  134,
      124,  124,  124,  124,  124,  124,  124,  124,  134,  135,

      137,  138,  141,  148,  149,  150,  156,  152,  135,  137,
      138,  141,  147,  160,  161,  163,  164,  166,  173,  173,
      156,  134,  168,  179,  179,  179,  148,  160,  150,  149,
      152,  135,  137,  138,  141,  166,  168,  161,  163,  164,
      171,  174,  174,  174,  174,  174,  175,  175,  175,  175,
      176,  176,  176,  176,  176,  176,  173,  218,  217,  173,
      205,  173,  205,  173,  173,  205,  173,  178,  178,  178,
      178,  178,  178,  181,  181,  181,  181,  237,  171,  180,
      180,  180,  180,  180,  180,  182,  182,  182,  182,  182,
      182,  171,  190,  190,  237,  171,  216,  171,  171,  171,

      171,  171,  171,  171,  171,  172,  185,  185,  185,  185,
      185,  185,  186,  186,  186,  186,  186,  186,  187,  187,
      187,  187,  187,  187,  191,  191,  191,  191,  191,  207,
      190,  207,  215,  190,  207,  190,  219,  190,  190,  214,
      190,  220,  213,  172,  192,  192,  192,  192,  193,  193,
      193,  193,  193,  193,  209,  220,  172,  194,  194,  194,
      172,  219,  172,  172,  172,  172,  172,  172,  172,  172,
      184,  195,  195,  195,  195,  195,  195,  196,  196,  196,
      197,  197,  197,  197,  197,  197,  198,  198,  198,  198,
      199,  199,  199,  199,  199,  199,  202,  202,  202,  202,

      202,  202,  203,  203,  203,  203,  203,  203,  184,  204,
      204,  204,  204,  204,  204,  206,  208,  210,  212,  210,
      212,  184,  210,  212,  206,  184,  221,  184,  184,  184,
      184,  184,  184,  184,  184,  188,  211,  222,  225,  228,
      221,  230,  231,  233,  232,  211,  200,  206,  236,  183,
      238,  269,  225,  228,  170,  222,  231,  233,  242,  242,
      242,  242,  242,  242,  230,  269,  276,  270,  211,  232,
      278,  236,  188,  238,  244,  244,  244,  244,  244,  244,
      276,  169,  167,  165,  278,  188,  162,  157,  151,  188,
      270,  188,  188,  188,  188,  188,  188,  188,  188,  189,

      245,  245,  245,  245,  245,  245,  246,  246,  246,  246,
      246,  246,  247,  247,  247,  247,  247,  247,  248,  248,
      248,  248,  248,  248,  249,  249,  249,  249,  249,  249,
      250,  250,  250,  250,  250,  250,  189,  252,  252,  252,
      252,  252,  252,  254,  254,  254,  254,  254,  254,  189,
      146,  144,  143,  189,  126,  189,  189,  189,  189,  189,
      189,  189,  189,  201,  255,  255,  255,  255,  255,  255,
      256,  256,  256,  256,  256,  256,  257,  257,  257,  257,
      257,  257,  258,  258,  258,  258,  258,  258,  259,  259,
      259,  259,  259,  259,  260,  260,  260,  260,  260,  260,

      201,  280,  312,  115,  111,  272,  279,  288,  288,  288,
      288,  288,  288,  201,  110,  280,  312,  201,  108,  201,
      201,  201,  201,  201,  201,  201,  201,  241,  272,  279,
      289,  289,  289,  289,  289,  289,  290,  290,  290,  290,
      290,  290,  293,  293,  293,  293,  293,  293,  294,  294,
      294,  294,  294,  294,  295,  295,  295,  295,  295,  295,
      300,  103,  303,   96,   94,  241,   93,   90,   83,   74,
      306,  311,   72,   71,   60,   58,   47,  300,  241,  303,
       43,   40,  241,   30,  241,  241,  241,  241,  241,  241,
      241,  241,  251,  306,  311,   23,   21,   17,    8,    7,

        5,    3,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  251,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  251,    0,    0,    0,  251,    0,  251,  251,
      251,  251,  251,  251,  251,  251,  287,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  287,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,  287,    0,    0,
        0,  287,    0,  287,  287,  287,  287,  287,  287,  287,
      287,  292,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  292,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  292,    0,    0,    0,  292,    0,  292,  292,  292,
      292,  292,  292,  292,  292,  315,    0,  315,  316,    0,
      316,  318,  318,  318,  319,  319,  319,  314,  314,  314,

      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  314,  314,  314,  314,  314
    } ;

static yyconst flex_int16_t yy_rule_linenum[65] =
    {   0,
      143,  144,  145,  146,  147,  148,  149,  150,  151,  152,
      153,  154,  155,  156,  157,  158,  159,  160,  161,  162,
      163,  164,  165,  166,  167,  168,  169,  170,  171,  172,
      173,  174,  175,  176,  177,  178,  179,  180,  181,  182,
      183,  184,  185,  186,  187,  188,  189,  190,  191,  192,
      193,  194,  195,  196,  197,  198,  199,  200,  201,  202,
      203,  204,  205,  208
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lib/SQLScanner.lpp"
/* $Id: Langname_Scanner.ll,v 1.1 2008/04/06 17:10:46 eric Exp SQLScanner.ll 28 2007-08-20 10:27:39Z tb $ -*- mode: c++ -*- */
/** \file SQLScanner.ll Define the Flex lexical scanner */
#line 5 "lib/SQLScanner.lpp"

#include <vector>
#include <sstream>


#include "SQL.hpp"
#include "SQLParser/SQLParser.hpp"
#include "SQLScanner.hpp"

/* import the parser's token type into a local typedef */
typedef w3c_sw::SQLParser::token token;
typedef w3c_sw::SQLParser::token_type token_type;

/* Work around an incompatibility in flex (at least versions 2.5.31 through
 * 2.5.33): it generates code that does not conform to C89.  See Debian bug
 * 333231 <http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=333231>.  */
// #undef yywrap	// ##flex2.5
// #define yywrap() 1	// ##flex2.5

/* By default yylex returns int, we use token_type. Unfortunately yyterminate
 * by default returns 0, which is not of token_type. */
#define yyterminate() return token::__EOF__

/* This disables inclusion of unistd.h, which is not available under Visual C++
 * on Win32. The C++ scanner uses STL streams instead. */
#define YY_NO_UNISTD_H

/*** Flex Declarations and Options ***/
/* enable c++ scanner class generation */
/* change the name of the scanner class. results in "SQLFlexLexer" */
/* consider using class instead
 * %option yyclass="SQLScanner"
 * void SQLFlexLexer::LexerError( yyconst char msg[] )
 */
/* the manual says "somewhat more optimized" */
/* enable scanner to generate debug output. disable this for release
 * versions. */
/* no support for include files is planned */
/* enables the use of start condition stacks */
/* The following paragraph suffices to track locations accurately. Each time
 * yylex is invoked, the begin position is moved onto the end position. */
#line 65 "lib/SQLScanner.lpp"
#define YY_USER_ACTION  yylloc->columns(yyleng);
#define YY_FATAL_ERROR(msg) do {		\
    throw msg;   \
} while(0)
/* START patterns for SQL terminals */
/*" for syntax hilighting */
/* END patterns for SQL terminals */
/* START semantic actions for SQL terminals */
#line 940 "lib/SQLScanner.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#include <unistd.h>
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */
/* %if-bison-bridge */
/* %endif */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define ECHO LexerOutput( yytext, yyleng )
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
\
/* %if-c++-only C++ definition \ */\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#define YY_FATAL_ERROR(msg) LexerError( msg )
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define YY_DECL int yyFlexLexer::yylex()
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 142 "lib/SQLScanner.lpp"

#line 1104 "lib/SQLScanner.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyin = & std::cin;
/* %endif */

		if ( ! yyout )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyout = & std::cout;
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 315 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 314 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				std::cerr << "--scanner backing up\n";
			else if ( yy_act < 65 )
				std::cerr << "--accepting rule at line " << yy_rule_linenum[yy_act] <<
				         "(\"" << yytext << "\")\n";
			else if ( yy_act == 65 )
				std::cerr << "--accepting default rule (\"" << yytext << "\")\n";
			else if ( yy_act == 66 )
				std::cerr << "--(end of buffer or a NUL)\n";
			else
				std::cerr << "--EOF (start condition " << YY_START << ")\n";
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 143 "lib/SQLScanner.lpp"
{ yylloc->end.lines(1); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 144 "lib/SQLScanner.lpp"
{ yylloc->step(); /* @@ needed? useful? */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 145 "lib/SQLScanner.lpp"
{return token::GT_SEMI;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 146 "lib/SQLScanner.lpp"
{return token::IT_CREATE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 147 "lib/SQLScanner.lpp"
{return token::IT_TABLE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 148 "lib/SQLScanner.lpp"
{return token::GT_LPAREN;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 149 "lib/SQLScanner.lpp"
{return token::GT_RPAREN;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 150 "lib/SQLScanner.lpp"
{return token::GT_COMMA;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 151 "lib/SQLScanner.lpp"
{return token::IT_FOREIGN;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 152 "lib/SQLScanner.lpp"
{return token::IT_KEY;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 153 "lib/SQLScanner.lpp"
{return token::IT_REFERENCES;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 154 "lib/SQLScanner.lpp"
{return token::IT_PRIMARY;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 155 "lib/SQLScanner.lpp"
{return token::IT_INT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 156 "lib/SQLScanner.lpp"
{return token::IT_DOUBLE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 157 "lib/SQLScanner.lpp"
{return token::IT_DATE;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 158 "lib/SQLScanner.lpp"
{return token::IT_DATETIME;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 159 "lib/SQLScanner.lpp"
{return token::IT_STRING;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 160 "lib/SQLScanner.lpp"
{return token::IT_SELECT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 161 "lib/SQLScanner.lpp"
{return token::IT_UNION;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 162 "lib/SQLScanner.lpp"
{return token::IT_WHERE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 163 "lib/SQLScanner.lpp"
{return token::IT_FROM;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 164 "lib/SQLScanner.lpp"
{return token::IT_LIMIT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 165 "lib/SQLScanner.lpp"
{return token::IT_OFFSET;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 166 "lib/SQLScanner.lpp"
{return token::GT_TIMES;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 167 "lib/SQLScanner.lpp"
{return token::IT_AS;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 168 "lib/SQLScanner.lpp"
{return token::GT_DOT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 169 "lib/SQLScanner.lpp"
{return token::IT_INNER;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 170 "lib/SQLScanner.lpp"
{return token::IT_LEFT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 171 "lib/SQLScanner.lpp"
{return token::IT_OUTER;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 172 "lib/SQLScanner.lpp"
{return token::IT_ON;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 173 "lib/SQLScanner.lpp"
{return token::IT_JOIN;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 174 "lib/SQLScanner.lpp"
{return token::IT_OR;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 175 "lib/SQLScanner.lpp"
{return token::IT_AND;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 176 "lib/SQLScanner.lpp"
{return token::GT_EQUAL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 177 "lib/SQLScanner.lpp"
{return token::GT_NEQUAL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 178 "lib/SQLScanner.lpp"
{return token::GT_LT;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 179 "lib/SQLScanner.lpp"
{return token::GT_GT;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 180 "lib/SQLScanner.lpp"
{return token::GT_LE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 181 "lib/SQLScanner.lpp"
{return token::GT_GE;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 182 "lib/SQLScanner.lpp"
{return token::IT_IS;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 183 "lib/SQLScanner.lpp"
{return token::IT_NULL;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 184 "lib/SQLScanner.lpp"
{return token::IT_NOT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 185 "lib/SQLScanner.lpp"
{return token::GT_PLUS;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 186 "lib/SQLScanner.lpp"
{return token::GT_MINUS;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 187 "lib/SQLScanner.lpp"
{return token::GT_DIVIDE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 188 "lib/SQLScanner.lpp"
{return token::GT_NOT;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 189 "lib/SQLScanner.lpp"
{return token::IT_CONCAT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 190 "lib/SQLScanner.lpp"
{return token::IT_true;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 191 "lib/SQLScanner.lpp"
{return token::IT_false;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 192 "lib/SQLScanner.lpp"
{yylval->p_NAME = new std::string(yytext); return token::NAME;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 193 "lib/SQLScanner.lpp"
{return typedLiteral(yylval, token::INTEGER);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 194 "lib/SQLScanner.lpp"
{return typedLiteral(yylval, token::DECIMAL);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 195 "lib/SQLScanner.lpp"
{return typedLiteral(yylval, token::DOUBLE);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 196 "lib/SQLScanner.lpp"
{return typedLiteral(yylval, token::INTEGER_POSITIVE);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 197 "lib/SQLScanner.lpp"
{return typedLiteral(yylval, token::DECIMAL_POSITIVE);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 198 "lib/SQLScanner.lpp"
{return typedLiteral(yylval, token::DOUBLE_POSITIVE);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 199 "lib/SQLScanner.lpp"
{return typedLiteral(yylval, token::INTEGER_NEGATIVE);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 200 "lib/SQLScanner.lpp"
{return typedLiteral(yylval, token::DECIMAL_NEGATIVE);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 201 "lib/SQLScanner.lpp"
{return typedLiteral(yylval, token::DOUBLE_NEGATIVE);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 202 "lib/SQLScanner.lpp"
{return unescape(yylval, yylloc, 1, token::STRING_LITERAL1);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 203 "lib/SQLScanner.lpp"
{return unescape(yylval, yylloc, 1, token::STRING_LITERAL2);}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 204 "lib/SQLScanner.lpp"
{return unescape(yylval, yylloc, 3, token::STRING_LITERAL_LONG1);}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 205 "lib/SQLScanner.lpp"
{return unescape(yylval, yylloc, 3, token::STRING_LITERAL_LONG2);}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 207 "lib/SQLScanner.lpp"
{ yyterminate();}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 208 "lib/SQLScanner.lpp"
{
    std::stringstream s;
    s << "unexpected input '" << yytext << "' at " << *yylloc;
    throw s.str();
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 214 "lib/SQLScanner.lpp"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1549 "lib/SQLScanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = 0;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	SQLfree(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	SQLfree(yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if ( new_in )
		{
		yy_delete_buffer( YY_CURRENT_BUFFER );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );
		}

	if ( new_out )
		yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout->write( buf, size );
}
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yy_get_next_buffer()
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					SQLrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) SQLrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_get_previous_state()
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 315 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 315 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 314);

	return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyunput( int c, register char* yy_bp)
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yyinput()
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyrestart( std::istream* input_file )
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_load_buffer_state()
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) SQLalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) SQLalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		SQLfree((void *) b->yy_ch_buf  );

	SQLfree((void *) b  );
}

/* %if-c-only */
/* %endif */

/* %if-c++-only */

extern "C" int isatty (int ) throw();

/* %endif */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_is_interactive = 0;
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypop_buffer_state (void)
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyensure_buffer_stack(void)
/* %endif */
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)SQLalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)SQLrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_push_state( int new_state )
/* %endif */
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) SQLalloc(new_size  );

		else
			(yy_start_stack) = (int *) SQLrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_pop_state()
/* %endif */
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yy_top_state()
/* %endif */
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::LexerError( yyconst char msg[] )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* %if-reentrant */
/* %endif */
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *SQLalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *SQLrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void SQLfree (void * ptr )
{
	free( (char *) ptr );	/* see SQLrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 214 "lib/SQLScanner.lpp"


/* END semantic actions for SQL terminals */

/* START SQLScanner */
namespace w3c_sw {

SQLScanner::SQLScanner(SQLDriver* driver, std::istream* in,
		 std::ostream* out)
    : SQLFlexLexer(in, out), driver(driver)
{
}

SQLScanner::~SQLScanner()
{
}

SQLParser::token_type SQLScanner::typedLiteral (SQLParser::semantic_type*& yylval, SQLParser::token_type tok) {
    std::istringstream is(yytext);

    switch (tok) {
    case token::INTEGER:
    case token::INTEGER_POSITIVE:
    case token::INTEGER_NEGATIVE:
	int i;
	is >> i;
	yylval->p_Expression = new sql::IntConstraint(i);
	return tok;
    case token::DECIMAL:
    case token::DECIMAL_POSITIVE:
    case token::DECIMAL_NEGATIVE:
	float f;
	is >> f;
	yylval->p_Expression = new sql::FloatConstraint(i);
	return tok;
    case token::DOUBLE:
    case token::DOUBLE_POSITIVE:
    case token::DOUBLE_NEGATIVE:
	double d;
	is >> d;
	yylval->p_Expression = new sql::DoubleConstraint(i);
	return tok;
    default: throw(new std::exception());
    }
}

    SQLParser::token_type SQLScanner::unescape (SQLParser::semantic_type*& yylval, w3c_sw::location* yylloc, size_t skip, SQLParser::token_type tok){
    std::string space;
    for (size_t i = skip; i < yyleng-skip; i++) {
	if (yytext[i] == '\\') {
	    switch (yytext[++i]) {
	    case 't':  space += '\t'; break;
	    case 'n':  space += '\n'; break;
	    case 'r':  space += '\r'; break;
	    case 'b':  space += '\b'; break;
	    case 'f':  space += '\f'; break;
	    case '"':  space += '\"'; break;
	    case '\'': space += '\''; break;
	    case '\\': space += '\\'; break;
	    default: throw(new std::exception());
	    }
	} else {
	    if (yytext[i] == '\r')
		yylloc->end.lines(1); 
	    else if (yytext[i] == '\n'
		     && !(i > skip && yytext[i-1] == '\r'))
		yylloc->end.lines(1); 
	    space += yytext[i];
	}
    }
    yylval->p_Expression = new sql::LiteralConstraint(space);
    return tok;
}


void SQLScanner::set_debug(bool b)
{
    yy_flex_debug = b;
}

} /* END SQLScanner */

/* This implementation of SQLFlexLexer::yylex() is required to fill the
 * vtable of the class SQLFlexLexer. We define the scanner's main yylex
 * function via YY_DECL to reside in the SQLScanner class instead. */

#ifdef yylex
#undef yylex
#endif

int SQLFlexLexer::yylex()
{
    std::cerr << "in SQLFlexLexer::yylex() !" << std::endl;
    return 0;
}


