// $Id: TrigScanner.hpp,v 1.3 2008-10-03 07:06:03 eric Exp $

#ifndef TrigScanner_H
#define TrigScanner_H

// Flex expects the signature of yylex to be defined in the macro YY_DECL, and
// the C++ parser expects it to be declared. We can factor both as follows.

#ifndef YY_DECL

#define	YY_DECL						\
    w3c_sw::TrigParser::token_type				\
    w3c_sw::TrigScanner::lex(				\
	w3c_sw::TrigParser::semantic_type* yylval,		\
	w3c_sw::TrigParser::location_type* yylloc		\
    )
#endif

#ifndef __FLEX_LEXER_H
#define yyFlexLexer TrigFlexLexer
#include "FlexLexer.h"
#undef yyFlexLexer
#endif

#include "TrigParser.hpp"

namespace w3c_sw {

/** TrigScanner is a derived class to add some extra function to the scanner
 * class. Flex itself creates a class named yyFlexLexer, which is renamed using
 * macros to TrigFlexLexer. However we change the context of the generated
 * yylex() function to be contained within the TrigScanner class. This is required
 * because the yylex() defined in TrigFlexLexer has no parameters. */
class TrigScanner : public TrigFlexLexer
{
private:
    TrigDriver* driver;
public:
    /** Create a new scanner object. The streams arg_yyin and arg_yyout default
     * to cin and cout, but that assignment is only made when initializing in
     * yylex(). */
    TrigScanner(TrigDriver* driver, std::istream* arg_yyin = 0,
	    std::ostream* arg_yyout = 0);

    /** Required for virtual functions */
    virtual ~TrigScanner();

    /** This is the main lexing function. It is generated by flex according to
     * the macro declaration YY_DECL above. The generated bison parser then
     * calls this virtual function to fetch new tokens. */
    virtual TrigParser::token_type lex(
	TrigParser::semantic_type* yylval,
	TrigParser::location_type* yylloc
	);
    TrigParser::token_type lexWrapper(
	   TrigParser::semantic_type* yylval,
	   TrigParser::location_type* yylloc
					   ) {
	try {
	    return lex(yylval, yylloc);
	} catch (const char* e) {
	    std::stringstream s;
	    s << *yylloc << ": " << e;
	    throw s.str();
	}
    }

    /** Enable debug output (via arg_yyout) if compiled into the scanner. */
    void set_debug(bool b);

    TrigParser::token_type typedLiteral(TrigParser::semantic_type*&, TrigParser::token_type tok);
    TrigParser::token_type unescape(TrigParser::semantic_type*&, size_t skip, TrigParser::token_type tok);
    const URI* resolvePrefix(const char*);
    const URI* resolveBase(const char*, bool stripDelims);
};

} // namespace w3c_sw

#endif // TrigScanner_H
