/* SQLclient_MySQL.hpp: implementation of SQLclient for ODBC.

 * $Id: SWObjects.hpp,v 1.26 2008-12-04 23:00:15 eric Exp $
 */

#include "../interface/SQLclient.hpp"

#ifndef INCLUDED_interface_SQLclient_ODBC_hpp
 #define INCLUDED_interface_SQLclient_ODBC_hpp

namespace odbc {
#include <sql.h>
#include <sqltypes.h>
#include <sqlext.h>
}

namespace w3c_sw {

    class SQLclient_ODBC : public SQLclient {
    protected:
	std::string driver;
	odbc::SQLHENV env;
	odbc::SQLHDBC dbc;
	std::string server, database, user;

	/**
	 * throwFailure - throw as informative an error as we can muster.
	 * @param leader	context error string to start the exception text.
	 * @param type		the type of handle: SQL_HANDLE_ENV | SQL_HANDLE_DBC | SQL_HANDLE_STMT | SQL_HANDLE_DESC
	 * @param handle	ODBC handle used in the failed operation.
	 */
	static void throwFailure (std::string leader, odbc::SQLSMALLINT type, odbc::SQLHANDLE handle) {
	    odbc::SQLINTEGER	i = 0;
	    odbc::SQLRETURN	r;
	    std::stringstream ss;
	    ss << leader;
	    do {
		odbc::SQLINTEGER	native;
		odbc::SQLCHAR		state[7];
		odbc::SQLCHAR		text[256];
		odbc::SQLSMALLINT	len;
		if ((r = odbc::SQLGetDiagRec(type, handle, ++i, state,
					     &native, text, sizeof(text), &len )) == SQL_SUCCESS) {
		    if (i > 1)	// can have multiple lines in message.
			ss << "\n";
		    ss << state << ":" << i << ":" << native << ":" << text;
		}
	    } while (r == SQL_SUCCESS);
	    throw ss.str();
	}

	/**
	 * _connect - connect to the database using the credentials in SQLclient_ODBC#driver.
	 * The four parameters (server, database, user, password) are ignored.
	 */
	virtual void _connect (std::string, std::string, std::string, const char*) {
	    std::string conString;
	    if (!SQL_SUCCEEDED(odbc::SQLDriverConnect(dbc, NULL, (odbc::SQLCHAR*)driver.c_str(), SQL_NTS,
						  NULL, 0, NULL, SQL_DRIVER_COMPLETE)))
		throwFailure("SQLDriverConnect failed: ", SQL_HANDLE_DBC, dbc);
	}

    public:

	/**
	 * SQLclient_ODBC::Result - ODBC-specific SQLclient::Result (row).
	 */
	class Result : public SQLclient::Result {
	protected:
	    odbc::SQLHSTMT stmt;
	    odbc::SQLSMALLINT num_fields;
	    ColumnSet colSet;
	    std::vector<odbc::SQLSMALLINT> sqlColTypes;
	    Row row;

	public:

	    /**
	     * SQLclient_ODBC::Result constructor.
	     * @param stmt	handle used in SQLExec.
	     */
	    Result (odbc::SQLHSTMT stmt) : stmt(stmt) {
		if (!SQL_SUCCEEDED(odbc::SQLNumResultCols(stmt, &num_fields)))
		    throwFailure("SQLNumResultCols failed: ", SQL_HANDLE_STMT, stmt);
		for(int i = 0; i < num_fields; i++) {
		    odbc::SQLCHAR	colname [32];
		    odbc::SQLSMALLINT	colnamelen;
		    odbc::SQLSMALLINT	coltype;
		    odbc::SQLULEN	collen;
		    odbc::SQLSMALLINT	scale;
		    odbc::SQLSMALLINT	nullable;

		    if (!SQL_SUCCEEDED(odbc::SQLDescribeCol(stmt, (odbc::SQLSMALLINT) (i + 1),
							colname, (odbc::SQLSMALLINT) sizeof(colname),
							&colnamelen, &coltype, &collen,
							&scale, &nullable)))
			throwFailure("SQLDescribeCol failed: ", SQL_HANDLE_STMT, stmt);

		    // Create a field to store the name and RDF type of this column.
		    Field f;
		    f.name = std::string((const char*)colname, colnamelen);
		    switch (coltype) {
		    case SQL_DECIMAL:
			f.type = Field::TYPE_decimal;
			break;
		    case SQL_CHAR:
			f.type = Field::TYPE_short;
			break;
		    case SQL_SMALLINT:
			f.type = Field::TYPE_short;
			break;
		    case SQL_NUMERIC:
			f.type = Field::TYPE_long;
			break;
		    case SQL_FLOAT:
			f.type = Field::TYPE_float;
			break;
		    case SQL_DOUBLE:
			f.type = Field::TYPE_double;
			break;
		    case SQL_REAL:
			f.type = Field::TYPE_decimal;
			break;
		    case SQL_INTEGER:
			f.type = Field::TYPE_integer;
			break;
		    case SQL_DATETIME:
		    case SQL_TIMESTAMP:
			f.type = Field::TYPE_dateTime;
			break;
		    case SQL_VARCHAR:
			f.type = Field::TYPE__literal;
			break;
		    default:
			if (true) { // do we want a switch to allow unknown datatypes?
			    std::stringstream s;
			    s << "fields[" << i << "] " << colname << " of unknown type " << coltype;
			    throw s.str();
			}
			f.type = Field::TYPE__unknown;
		    }

		    colSet.push_back(f); 		// Store the new Field.
		    sqlColTypes.push_back(coltype);	// Also store the SQL-native type.
		}
	    }

	    virtual ColumnSet& cols () { return colSet; }

	    /**
	     * nextRow: create a Row record for the next fetchable row.
	     * @returns: SQLclient::Row, or SQLclient::Result.end() if at the end.
	     */
	    virtual Row nextRow () {
		Row ret;
		if (!SQL_SUCCEEDED(odbc::SQLFetch(stmt)))
		    return ret; // returns SQLclient::Result.end()
		// could throwFailure(SQL_HANDLE_STMT, stmt) if it's the wrong error.

		// For each column:
		for(odbc::SQLSMALLINT i = 0; i < num_fields; i++) {

		    /* retrieve column data as a string */
		    odbc::SQLLEN indicator;
		    char buf[512];
		    if (!SQL_SUCCEEDED(odbc::SQLGetData(stmt, i+1, SQL_C_CHAR,
						    buf, sizeof(buf), &indicator)))
			throwFailure("SQLGetData failed: ", SQL_HANDLE_STMT, stmt);
		    if (indicator == SQL_NULL_DATA) {
			ret.push_back(OptString());
		    } else {
			std::string lexval(buf);

			// Perform necessary SQL-to-RDF lexical transformations:
			switch (sqlColTypes[i]) {
			case SQL_DATETIME:
			    lexval.replace(lexval.find_first_of(' '), 1, "T");
			    break;
			case SQL_TIMESTAMP:
			    lexval = "0-0-0T" + lexval;
			    break;
			default:
			    break;
			}

			ret.push_back(OptString(lexval, ""));
		    }
		}
		return ret;
	    }
	};

	/**
	 * SQLclient_ODBC constructor.
	 * @param driver	the ODBC connect string.
	 * We don't even try to parse out e.g. database and user names.
	 */
	SQLclient_ODBC (std::string driver) : SQLclient(), driver(driver) {
	    if (!SQL_SUCCEEDED(odbc::SQLAllocHandle(SQL_HANDLE_ENV, SQL_NULL_HANDLE, &env)))
		    throwFailure("SQLAllocHandle ENV failed: ", SQL_HANDLE_ENV, env);
	    if (!SQL_SUCCEEDED(odbc::SQLSetEnvAttr(env, SQL_ATTR_ODBC_VERSION, (void *) SQL_OV_ODBC3, 0)))
		    throwFailure("SQLSetEnvAttr failed: ", SQL_HANDLE_ENV, env);
	    if (!SQL_SUCCEEDED(odbc::SQLAllocHandle(SQL_HANDLE_DBC, env, &dbc)))
		    throwFailure("SQLAllocHandle DBC failed: ", SQL_HANDLE_DBC, env);
	}

	~SQLclient_ODBC () {  }

	virtual void connect (std::string server, std::string database, std::string user) {
	    _connect(server, database, user, NULL);
	}
	virtual void connect (std::string server, std::string database, std::string user, std::string password) {
	    _connect(server, database, user, password.c_str());
	}

	/**
	 * executeQuery - Execute a generic SQL query.
	 * @param query		the query string to send to the engine.
	 */
	virtual Result* executeQuery (std::string query, Result::Fixups& /* fixups */ = Result::Fixups::Empty) {
	    odbc::SQLHSTMT stmt;

	    if (!SQL_SUCCEEDED(odbc::SQLAllocHandle(SQL_HANDLE_STMT, dbc, &stmt)))
		throwFailure("SQLAllocHandle statement failed: ", SQL_HANDLE_STMT, env);
	    if (!SQL_SUCCEEDED(odbc::SQLExecDirect(stmt, (odbc::SQLCHAR*)query.c_str(), SQL_NTS)))
		throwFailure("SQLExecDirect failed: ", SQL_HANDLE_STMT, env);

	    return new Result(stmt);
	}
    };

} /* namespace w3c_sw */

#ifdef NEEDDEF_W3C_SW_SQLCLIENT
  #undef NEEDDEF_W3C_SW_SQLCLIENT
  #define W3C_SW_SQLCLIENT w3c_sw::SQLclient_ODBC
#endif /* NEEDDEF_W3C_SW_SQLCLIENT */

#endif // !INCLUDED_interface_SQLclient_ODBC_hpp

/* Add extra return code debugging info someday:
		odbc::SQLRETURN r;
		if (!(SQL_SUCCEEDED(r = ::SQLFetch(stmt)))) {
		    std::stringstream ss;
		    ss << __FILE__ << "(" << __LINE__ << "): error: SQLFetch failed with " << r << "(" <<
			(r == SQL_SUCCESS ? "SQL_SUCCESS" :
			 r == SQL_SUCCESS_WITH_INFO ? "SQL_SUCCESS_WITH_INFO" :
			 r == SQL_NO_DATA ? "SQL_NO_DATA" :
			 r == SQL_STILL_EXECUTING ? "SQL_STILL_EXECUTING" :
			 r == SQL_ERROR ? "SQL_ERROR" :
			 r == SQL_INVALID_HANDLE ? "SQL_INVALID_HANDLE" :
			 "???")
		       << "): ";
		    sql.throwFailure(ss.str(), SQL_HANDLE_STMT, (stmt);
		}

 */

/*
 * 
 */
// undef sqlext.h artifacts
#undef SQLTables_TABLE_CATALOG
#undef SQLTables_TABLE_SCHEM
#undef SQLTables_TABLE_NAME
#undef SQLTables_TABLE_TYPE
#undef SQLTables_REMARKS
#undef SQLColumns_TABLE_CAT
#undef SQLColumns_TABLE_SCHEM
#undef SQLColumns_TABLE_NAME
#undef SQLColumns_COLUMN_NAME
#undef SQLColumns_DATA_TYPE
#undef SQLColumns_TYPE_NAME
#undef SQLColumns_COLUMN_SIZE
#undef SQLColumns_BUFFER_LENGTH
#undef SQLColumns_DECIMAL_DIGITS
#undef SQLColumns_NUM_PREC_RADIX
#undef SQLColumns_NULLABLE
#undef SQLColumns_REMARKS
#undef SQLColumns_COLUMN_DEF
#undef SQLColumns_SQL_DATA_TYPE
#undef SQLColumns_SQL_DATETIME_SUB
#undef SQLColumns_CHAR_OCTET_LENGTH
#undef SQLColumns_ORDINAL_POSITION
#undef SQLColumns_IS_NULLABLE
#undef SQL_SPEC_MAJOR
#undef SQL_SPEC_MINOR
#undef SQL_SPEC_STRING
#undef SQL_SQLSTATE_SIZE
#undef SQL_MAX_DSN_LENGTH
#undef SQL_MAX_OPTION_STRING_LENGTH
#undef SQL_NO_DATA_FOUND
#undef SQL_NO_DATA_FOUND
#undef	SQL_HANDLE_SENV
#undef SQL_ATTR_ODBC_VERSION
#undef SQL_ATTR_CONNECTION_POOLING
#undef SQL_ATTR_CP_MATCH
#undef SQL_ATTR_UNIXODBC_SYSPATH
#undef SQL_ATTR_UNIXODBC_VERSION
#undef SQL_ATTR_UNIXODBC_ENVATTR
#undef SQL_CP_OFF
#undef SQL_CP_ONE_PER_DRIVER
#undef SQL_CP_ONE_PER_HENV
#undef SQL_CP_DEFAULT
#undef SQL_CP_STRICT_MATCH
#undef SQL_CP_RELAXED_MATCH
#undef SQL_CP_MATCH_DEFAULT
#undef SQL_OV_ODBC2
#undef	SQL_OV_ODBC3
#undef SQL_ACCESS_MODE
#undef SQL_AUTOCOMMIT
#undef SQL_LOGIN_TIMEOUT
#undef SQL_OPT_TRACE
#undef SQL_OPT_TRACEFILE
#undef SQL_TRANSLATE_DLL
#undef SQL_TRANSLATE_OPTION
#undef SQL_TXN_ISOLATION
#undef SQL_CURRENT_QUALIFIER
#undef SQL_ODBC_CURSORS
#undef SQL_QUIET_MODE
#undef SQL_PACKET_SIZE
#undef SQL_ATTR_ACCESS_MODE
#undef SQL_ATTR_AUTOCOMMIT
#undef SQL_ATTR_CONNECTION_TIMEOUT
#undef SQL_ATTR_CURRENT_CATALOG
#undef SQL_ATTR_DISCONNECT_BEHAVIOR
#undef SQL_ATTR_ENLIST_IN_DTC
#undef SQL_ATTR_ENLIST_IN_XA
#undef SQL_ATTR_LOGIN_TIMEOUT
#undef SQL_ATTR_ODBC_CURSORS
#undef SQL_ATTR_PACKET_SIZE
#undef SQL_ATTR_QUIET_MODE
#undef SQL_ATTR_TRACE
#undef SQL_ATTR_TRACEFILE
#undef SQL_ATTR_TRANSLATE_LIB
#undef SQL_ATTR_TRANSLATE_OPTION
#undef SQL_ATTR_TXN_ISOLATION
#undef SQL_ATTR_CONNECTION_DEAD
#undef SQL_ATTR_DRIVER_THREADING
#undef SQL_ATTR_ANSI_APP
#undef SQL_CONNECT_OPT_DRVR_START
#undef SQL_CONN_OPT_MAX
#undef SQL_CONN_OPT_MIN
#undef SQL_MODE_READ_WRITE
#undef SQL_MODE_READ_ONLY
#undef SQL_MODE_DEFAULT
#undef SQL_AUTOCOMMIT_OFF
#undef SQL_AUTOCOMMIT_ON
#undef SQL_AUTOCOMMIT_DEFAULT
#undef SQL_LOGIN_TIMEOUT_DEFAULT
#undef SQL_OPT_TRACE_OFF
#undef SQL_OPT_TRACE_ON
#undef SQL_OPT_TRACE_DEFAULT
#undef SQL_OPT_TRACE_FILE_DEFAULT
#undef SQL_CUR_USE_IF_NEEDED
#undef SQL_CUR_USE_ODBC
#undef SQL_CUR_USE_DRIVER
#undef SQL_CUR_DEFAULT
#undef SQL_DB_RETURN_TO_POOL
#undef SQL_DB_DISCONNECT
#undef SQL_DB_DEFAULT
#undef SQL_DTC_DONE
#undef SQL_CD_TRUE
#undef SQL_CD_FALSE
#undef SQL_AA_TRUE
#undef SQL_AA_FALSE
#undef SQL_QUERY_TIMEOUT
#undef SQL_MAX_ROWS
#undef SQL_NOSCAN
#undef SQL_MAX_LENGTH
#undef SQL_ASYNC_ENABLE
#undef SQL_BIND_TYPE
#undef SQL_CURSOR_TYPE
#undef SQL_CONCURRENCY
#undef SQL_KEYSET_SIZE
#undef SQL_ROWSET_SIZE
#undef SQL_SIMULATE_CURSOR
#undef SQL_RETRIEVE_DATA
#undef SQL_USE_BOOKMARKS
#undef SQL_GET_BOOKMARK
#undef SQL_ROW_NUMBER
#undef SQL_ATTR_ASYNC_ENABLE
#undef SQL_ATTR_CONCURRENCY
#undef SQL_ATTR_CURSOR_TYPE
#undef	SQL_ATTR_ENABLE_AUTO_IPD
#undef SQL_ATTR_FETCH_BOOKMARK_PTR
#undef SQL_ATTR_KEYSET_SIZE
#undef SQL_ATTR_MAX_LENGTH
#undef SQL_ATTR_MAX_ROWS
#undef SQL_ATTR_NOSCAN
#undef SQL_ATTR_PARAM_BIND_OFFSET_PTR
#undef	SQL_ATTR_PARAM_BIND_TYPE
#undef SQL_ATTR_PARAM_OPERATION_PTR
#undef SQL_ATTR_PARAM_STATUS_PTR
#undef	SQL_ATTR_PARAMS_PROCESSED_PTR
#undef	SQL_ATTR_PARAMSET_SIZE
#undef SQL_ATTR_QUERY_TIMEOUT
#undef SQL_ATTR_RETRIEVE_DATA
#undef SQL_ATTR_ROW_BIND_OFFSET_PTR
#undef	SQL_ATTR_ROW_BIND_TYPE
#undef SQL_ATTR_ROW_NUMBER
#undef SQL_ATTR_ROW_OPERATION_PTR
#undef	SQL_ATTR_ROW_STATUS_PTR
#undef	SQL_ATTR_ROWS_FETCHED_PTR
#undef SQL_ATTR_ROW_ARRAY_SIZE
#undef SQL_ATTR_SIMULATE_CURSOR
#undef SQL_ATTR_USE_BOOKMARKS
#undef SQL_STMT_OPT_MAX
#undef SQL_STMT_OPT_MIN
#undef	SQL_COL_PRED_CHAR
#undef	SQL_COL_PRED_BASIC
#undef SQL_IS_POINTER
#undef SQL_IS_UINTEGER
#undef SQL_IS_INTEGER
#undef SQL_IS_USMALLINT
#undef SQL_IS_SMALLINT
#undef SQL_PARAM_BIND_BY_COLUMN
#undef SQL_PARAM_BIND_TYPE_DEFAULT
#undef SQL_QUERY_TIMEOUT_DEFAULT
#undef SQL_MAX_ROWS_DEFAULT
#undef SQL_NOSCAN_OFF
#undef SQL_NOSCAN_ON
#undef SQL_NOSCAN_DEFAULT
#undef SQL_MAX_LENGTH_DEFAULT
#undef SQL_ASYNC_ENABLE_OFF
#undef SQL_ASYNC_ENABLE_ON
#undef SQL_ASYNC_ENABLE_DEFAULT
#undef SQL_BIND_BY_COLUMN
#undef SQL_BIND_TYPE_DEFAULT
#undef SQL_CONCUR_READ_ONLY
#undef SQL_CONCUR_LOCK
#undef SQL_CONCUR_ROWVER
#undef SQL_CONCUR_VALUES
#undef SQL_CONCUR_DEFAULT
#undef SQL_CURSOR_FORWARD_ONLY
#undef SQL_CURSOR_KEYSET_DRIVEN
#undef SQL_CURSOR_DYNAMIC
#undef SQL_CURSOR_STATIC
#undef SQL_CURSOR_TYPE_DEFAULT
#undef SQL_ROWSET_SIZE_DEFAULT
#undef SQL_KEYSET_SIZE_DEFAULT
#undef SQL_SC_NON_UNIQUE
#undef SQL_SC_TRY_UNIQUE
#undef SQL_SC_UNIQUE
#undef SQL_RD_OFF
#undef SQL_RD_ON
#undef SQL_RD_DEFAULT
#undef SQL_UB_OFF
#undef	SQL_UB_ON
#undef SQL_UB_DEFAULT
#undef SQL_UB_FIXED
#undef SQL_UB_VARIABLE
#undef SQL_DESC_ARRAY_SIZE
#undef SQL_DESC_ARRAY_STATUS_PTR
#undef SQL_DESC_AUTO_UNIQUE_VALUE
#undef SQL_DESC_BASE_COLUMN_NAME
#undef SQL_DESC_BASE_TABLE_NAME
#undef SQL_DESC_BIND_OFFSET_PTR
#undef SQL_DESC_BIND_TYPE
#undef SQL_DESC_CASE_SENSITIVE
#undef SQL_DESC_CATALOG_NAME
#undef SQL_DESC_CONCISE_TYPE
#undef SQL_DESC_DATETIME_INTERVAL_PRECISION
#undef SQL_DESC_DISPLAY_SIZE
#undef SQL_DESC_FIXED_PREC_SCALE
#undef SQL_DESC_LABEL
#undef SQL_DESC_LITERAL_PREFIX
#undef SQL_DESC_LITERAL_SUFFIX
#undef SQL_DESC_LOCAL_TYPE_NAME
#undef	SQL_DESC_MAXIMUM_SCALE
#undef SQL_DESC_MINIMUM_SCALE
#undef SQL_DESC_NUM_PREC_RADIX
#undef SQL_DESC_PARAMETER_TYPE
#undef SQL_DESC_ROWS_PROCESSED_PTR
#undef SQL_DESC_ROWVER
#undef SQL_DESC_SCHEMA_NAME
#undef SQL_DESC_SEARCHABLE
#undef SQL_DESC_TYPE_NAME
#undef SQL_DESC_TABLE_NAME
#undef SQL_DESC_UNSIGNED
#undef SQL_DESC_UPDATABLE
#undef SQL_DIAG_CURSOR_ROW_COUNT
#undef SQL_DIAG_ROW_NUMBER
#undef SQL_DIAG_COLUMN_NUMBER
#undef SQL_DATE
#undef SQL_INTERVAL
#undef SQL_TIME
#undef SQL_TIMESTAMP
#undef SQL_LONGVARCHAR
#undef SQL_BINARY
#undef SQL_VARBINARY
#undef SQL_LONGVARBINARY
#undef SQL_BIGINT
#undef SQL_TINYINT
#undef SQL_BIT
#undef SQL_GUID
#undef SQL_CODE_YEAR
#undef SQL_CODE_MONTH
#undef SQL_CODE_DAY
#undef SQL_CODE_HOUR
#undef SQL_CODE_MINUTE
#undef SQL_CODE_SECOND
#undef SQL_CODE_YEAR_TO_MONTH
#undef SQL_CODE_DAY_TO_HOUR
#undef SQL_CODE_DAY_TO_MINUTE
#undef SQL_CODE_DAY_TO_SECOND
#undef SQL_CODE_HOUR_TO_MINUTE
#undef SQL_CODE_HOUR_TO_SECOND
#undef SQL_CODE_MINUTE_TO_SECOND
#undef SQL_INTERVAL_YEAR
#undef SQL_INTERVAL_MONTH
#undef SQL_INTERVAL_DAY
#undef SQL_INTERVAL_HOUR
#undef SQL_INTERVAL_MINUTE
#undef SQL_INTERVAL_SECOND
#undef SQL_INTERVAL_YEAR_TO_MONTH
#undef SQL_INTERVAL_DAY_TO_HOUR
#undef SQL_INTERVAL_DAY_TO_MINUTE
#undef SQL_INTERVAL_DAY_TO_SECOND
#undef SQL_INTERVAL_HOUR_TO_MINUTE
#undef SQL_INTERVAL_HOUR_TO_SECOND
#undef SQL_INTERVAL_MINUTE_TO_SECOND
#undef SQL_INTERVAL_YEAR
#undef SQL_INTERVAL_MONTH
#undef SQL_INTERVAL_YEAR_TO_MONTH
#undef SQL_INTERVAL_DAY
#undef SQL_INTERVAL_HOUR
#undef SQL_INTERVAL_MINUTE
#undef SQL_INTERVAL_SECOND
#undef SQL_INTERVAL_DAY_TO_HOUR
#undef SQL_INTERVAL_DAY_TO_MINUTE
#undef SQL_INTERVAL_DAY_TO_SECOND
#undef SQL_INTERVAL_HOUR_TO_MINUTE
#undef SQL_INTERVAL_HOUR_TO_SECOND
#undef SQL_INTERVAL_MINUTE_TO_SECOND
#undef SQL_UNICODE
#undef SQL_UNICODE_VARCHAR
#undef SQL_UNICODE_LONGVARCHAR
#undef SQL_UNICODE_CHAR
#undef	SQL_UNICODE
#undef	SQL_UNICODE_VARCHAR
#undef SQL_UNICODE_LONGVARCHAR
#undef SQL_UNICODE_CHAR
#undef SQL_TYPE_DRIVER_START
#undef SQL_TYPE_DRIVER_END
#undef SQL_C_CHAR
#undef SQL_C_LONG
#undef SQL_C_SHORT
#undef SQL_C_FLOAT
#undef SQL_C_DOUBLE
#undef	SQL_C_NUMERIC
#undef SQL_C_DEFAULT
#undef SQL_SIGNED_OFFSET
#undef SQL_UNSIGNED_OFFSET
#undef SQL_C_DATE
#undef SQL_C_TIME
#undef SQL_C_TIMESTAMP
#undef SQL_C_TYPE_DATE
#undef SQL_C_TYPE_TIME
#undef SQL_C_TYPE_TIMESTAMP
#undef SQL_C_INTERVAL_YEAR
#undef SQL_C_INTERVAL_MONTH
#undef SQL_C_INTERVAL_DAY
#undef SQL_C_INTERVAL_HOUR
#undef SQL_C_INTERVAL_MINUTE
#undef SQL_C_INTERVAL_SECOND
#undef SQL_C_INTERVAL_YEAR_TO_MONTH
#undef SQL_C_INTERVAL_DAY_TO_HOUR
#undef SQL_C_INTERVAL_DAY_TO_MINUTE
#undef SQL_C_INTERVAL_DAY_TO_SECOND
#undef SQL_C_INTERVAL_HOUR_TO_MINUTE
#undef SQL_C_INTERVAL_HOUR_TO_SECOND
#undef SQL_C_INTERVAL_MINUTE_TO_SECOND
#undef SQL_C_BINARY
#undef SQL_C_BIT
#undef SQL_C_SBIGINT
#undef SQL_C_UBIGINT
#undef SQL_C_TINYINT
#undef SQL_C_SLONG
#undef SQL_C_SSHORT
#undef SQL_C_STINYINT
#undef SQL_C_ULONG
#undef SQL_C_USHORT
#undef SQL_C_UTINYINT
#undef SQL_C_BOOKMARK
#undef SQL_C_BOOKMARK
#undef SQL_C_GUID
#undef SQL_TYPE_NULL
#undef SQL_TYPE_MIN
#undef SQL_TYPE_MAX
#undef SQL_C_VARBOOKMARK
#undef SQL_NO_ROW_NUMBER
#undef SQL_NO_COLUMN_NUMBER
#undef SQL_ROW_NUMBER_UNKNOWN
#undef SQL_COLUMN_NUMBER_UNKNOWN
#undef SQL_DEFAULT_PARAM
#undef SQL_IGNORE
#undef SQL_COLUMN_IGNORE
#undef SQL_LEN_DATA_AT_EXEC_OFFSET
#undef SQL_LEN_DATA_AT_EXEC
#undef SQL_LEN_BINARY_ATTR_OFFSET
#undef SQL_LEN_BINARY_ATTR
#undef SQL_PARAM_TYPE_DEFAULT
#undef SQL_SETPARAM_VALUE_MAX
#undef SQL_COLUMN_COUNT
#undef SQL_COLUMN_NAME
#undef SQL_COLUMN_TYPE
#undef SQL_COLUMN_LENGTH
#undef SQL_COLUMN_PRECISION
#undef SQL_COLUMN_SCALE
#undef SQL_COLUMN_DISPLAY_SIZE
#undef SQL_COLUMN_NULLABLE
#undef SQL_COLUMN_UNSIGNED
#undef SQL_COLUMN_MONEY
#undef SQL_COLUMN_UPDATABLE
#undef SQL_COLUMN_AUTO_INCREMENT
#undef SQL_COLUMN_CASE_SENSITIVE
#undef SQL_COLUMN_SEARCHABLE
#undef SQL_COLUMN_TYPE_NAME
#undef SQL_COLUMN_TABLE_NAME
#undef SQL_COLUMN_OWNER_NAME
#undef SQL_COLUMN_QUALIFIER_NAME
#undef SQL_COLUMN_LABEL
#undef SQL_COLATT_OPT_MAX
#undef SQL_COLUMN_DRIVER_START
#undef SQL_COLATT_OPT_MIN
#undef SQL_ATTR_READONLY
#undef SQL_ATTR_WRITE
#undef SQL_ATTR_READWRITE_UNKNOWN
#undef SQL_UNSEARCHABLE
#undef SQL_LIKE_ONLY
#undef SQL_ALL_EXCEPT_LIKE
#undef SQL_SEARCHABLE
#undef SQL_PRED_SEARCHABLE
#undef SQL_NO_TOTAL
#undef SQL_API_SQLALLOCHANDLESTD
#undef SQL_API_SQLBULKOPERATIONS
#undef SQL_API_SQLBINDPARAMETER
#undef SQL_API_SQLBROWSECONNECT
#undef SQL_API_SQLCOLATTRIBUTES
#undef SQL_API_SQLCOLUMNPRIVILEGES
#undef SQL_API_SQLDESCRIBEPARAM
#undef	SQL_API_SQLDRIVERCONNECT
#undef SQL_API_SQLDRIVERS
#undef SQL_API_SQLEXTENDEDFETCH
#undef SQL_API_SQLFOREIGNKEYS
#undef SQL_API_SQLMORERESULTS
#undef SQL_API_SQLNATIVESQL
#undef SQL_API_SQLNUMPARAMS
#undef SQL_API_SQLPARAMOPTIONS
#undef SQL_API_SQLPRIMARYKEYS
#undef SQL_API_SQLPROCEDURECOLUMNS
#undef SQL_API_SQLPROCEDURES
#undef SQL_API_SQLSETPOS
#undef SQL_API_SQLSETSCROLLOPTIONS
#undef SQL_API_SQLTABLEPRIVILEGES
#undef SQL_EXT_API_LAST
#undef SQL_NUM_FUNCTIONS
#undef SQL_EXT_API_START
#undef SQL_NUM_EXTENSIONS
#undef SQL_API_ALL_FUNCTIONS
#undef SQL_API_LOADBYORDINAL
#undef SQL_API_ODBC3_ALL_FUNCTIONS
#undef	SQL_API_ODBC3_ALL_FUNCTIONS_SIZE
#undef SQL_FUNC_EXISTS
#undef SQL_INFO_FIRST
#undef SQL_ACTIVE_CONNECTIONS
#undef SQL_ACTIVE_STATEMENTS
#undef SQL_DRIVER_HDBC
#undef SQL_DRIVER_HENV
#undef SQL_DRIVER_HSTMT
#undef SQL_DRIVER_NAME
#undef SQL_DRIVER_VER
#undef SQL_ODBC_API_CONFORMANCE
#undef SQL_ODBC_VER
#undef SQL_ROW_UPDATES
#undef SQL_ODBC_SAG_CLI_CONFORMANCE
#undef SQL_ODBC_SQL_CONFORMANCE
#undef SQL_PROCEDURES
#undef SQL_CONCAT_NULL_BEHAVIOR
#undef SQL_CURSOR_ROLLBACK_BEHAVIOR
#undef SQL_EXPRESSIONS_IN_ORDERBY
#undef SQL_MAX_OWNER_NAME_LEN
#undef SQL_MAX_PROCEDURE_NAME_LEN
#undef SQL_MAX_QUALIFIER_NAME_LEN
#undef SQL_MULT_RESULT_SETS
#undef SQL_MULTIPLE_ACTIVE_TXN
#undef SQL_OUTER_JOINS
#undef SQL_OWNER_TERM
#undef SQL_PROCEDURE_TERM
#undef SQL_QUALIFIER_NAME_SEPARATOR
#undef SQL_QUALIFIER_TERM
#undef SQL_SCROLL_OPTIONS
#undef SQL_TABLE_TERM
#undef SQL_CONVERT_FUNCTIONS
#undef SQL_NUMERIC_FUNCTIONS
#undef SQL_STRING_FUNCTIONS
#undef SQL_SYSTEM_FUNCTIONS
#undef SQL_TIMEDATE_FUNCTIONS
#undef SQL_CONVERT_BIGINT
#undef SQL_CONVERT_BINARY
#undef SQL_CONVERT_BIT
#undef SQL_CONVERT_CHAR
#undef SQL_CONVERT_DATE
#undef SQL_CONVERT_DECIMAL
#undef SQL_CONVERT_DOUBLE
#undef SQL_CONVERT_FLOAT
#undef SQL_CONVERT_INTEGER
#undef SQL_CONVERT_LONGVARCHAR
#undef SQL_CONVERT_NUMERIC
#undef SQL_CONVERT_REAL
#undef SQL_CONVERT_SMALLINT
#undef SQL_CONVERT_TIME
#undef SQL_CONVERT_TIMESTAMP
#undef SQL_CONVERT_TINYINT
#undef SQL_CONVERT_VARBINARY
#undef SQL_CONVERT_VARCHAR
#undef SQL_CONVERT_LONGVARBINARY
#undef SQL_CONVERT_GUID
#undef SQL_ODBC_SQL_OPT_IEF
#undef SQL_CORRELATION_NAME
#undef SQL_NON_NULLABLE_COLUMNS
#undef SQL_DRIVER_HLIB
#undef SQL_DRIVER_ODBC_VER
#undef SQL_LOCK_TYPES
#undef SQL_POS_OPERATIONS
#undef SQL_POSITIONED_STATEMENTS
#undef SQL_BOOKMARK_PERSISTENCE
#undef SQL_STATIC_SENSITIVITY
#undef SQL_FILE_USAGE
#undef SQL_COLUMN_ALIAS
#undef SQL_GROUP_BY
#undef SQL_KEYWORDS
#undef SQL_OWNER_USAGE
#undef SQL_QUALIFIER_USAGE
#undef SQL_QUOTED_IDENTIFIER_CASE
#undef SQL_SUBQUERIES
#undef SQL_UNION
#undef SQL_MAX_ROW_SIZE_INCLUDES_LONG
#undef SQL_MAX_CHAR_LITERAL_LEN
#undef SQL_TIMEDATE_ADD_INTERVALS
#undef SQL_TIMEDATE_DIFF_INTERVALS
#undef SQL_NEED_LONG_DATA_LEN
#undef SQL_MAX_BINARY_LITERAL_LEN
#undef SQL_LIKE_ESCAPE_CLAUSE
#undef SQL_QUALIFIER_LOCATION
#undef SQL_OJ_CAPABILITIES
#undef SQL_INFO_LAST
#undef SQL_INFO_DRIVER_START
#undef SQL_ACTIVE_ENVIRONMENTS
#undef	SQL_ALTER_DOMAIN
#undef	SQL_SQL_CONFORMANCE
#undef SQL_DATETIME_LITERALS
#undef	SQL_ASYNC_MODE
#undef SQL_BATCH_ROW_COUNT
#undef SQL_BATCH_SUPPORT
#undef SQL_CATALOG_LOCATION
#undef SQL_CATALOG_NAME_SEPARATOR
#undef SQL_CATALOG_TERM
#undef SQL_CATALOG_USAGE
#undef	SQL_CONVERT_WCHAR
#undef SQL_CONVERT_INTERVAL_DAY_TIME
#undef SQL_CONVERT_INTERVAL_YEAR_MONTH
#undef	SQL_CONVERT_WLONGVARCHAR
#undef	SQL_CONVERT_WVARCHAR
#undef	SQL_CREATE_ASSERTION
#undef	SQL_CREATE_CHARACTER_SET
#undef	SQL_CREATE_COLLATION
#undef	SQL_CREATE_DOMAIN
#undef	SQL_CREATE_SCHEMA
#undef	SQL_CREATE_TABLE
#undef	SQL_CREATE_TRANSLATION
#undef	SQL_CREATE_VIEW
#undef SQL_DRIVER_HDESC
#undef	SQL_DROP_ASSERTION
#undef	SQL_DROP_CHARACTER_SET
#undef	SQL_DROP_COLLATION
#undef	SQL_DROP_DOMAIN
#undef	SQL_DROP_SCHEMA
#undef	SQL_DROP_TABLE
#undef	SQL_DROP_TRANSLATION
#undef	SQL_DROP_VIEW
#undef SQL_DYNAMIC_CURSOR_ATTRIBUTES1
#undef SQL_DYNAMIC_CURSOR_ATTRIBUTES2
#undef SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES1
#undef SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES2
#undef SQL_INDEX_KEYWORDS
#undef SQL_INFO_SCHEMA_VIEWS
#undef SQL_KEYSET_CURSOR_ATTRIBUTES1
#undef SQL_KEYSET_CURSOR_ATTRIBUTES2
#undef	SQL_MAX_ASYNC_CONCURRENT_STATEMENTS
#undef SQL_ODBC_INTERFACE_CONFORMANCE
#undef SQL_PARAM_ARRAY_ROW_COUNTS
#undef SQL_PARAM_ARRAY_SELECTS
#undef SQL_SCHEMA_TERM
#undef SQL_SCHEMA_USAGE
#undef SQL_SQL92_DATETIME_FUNCTIONS
#undef SQL_SQL92_FOREIGN_KEY_DELETE_RULE
#undef SQL_SQL92_FOREIGN_KEY_UPDATE_RULE
#undef SQL_SQL92_GRANT
#undef SQL_SQL92_NUMERIC_VALUE_FUNCTIONS
#undef SQL_SQL92_PREDICATES
#undef SQL_SQL92_RELATIONAL_JOIN_OPERATORS
#undef SQL_SQL92_REVOKE
#undef SQL_SQL92_ROW_VALUE_CONSTRUCTOR
#undef SQL_SQL92_STRING_FUNCTIONS
#undef SQL_SQL92_VALUE_EXPRESSIONS
#undef SQL_STANDARD_CLI_CONFORMANCE
#undef SQL_STATIC_CURSOR_ATTRIBUTES1
#undef SQL_STATIC_CURSOR_ATTRIBUTES2
#undef SQL_AGGREGATE_FUNCTIONS
#undef SQL_DDL_INDEX
#undef SQL_DM_VER
#undef SQL_INSERT_STATEMENT
#undef SQL_UNION_STATEMENT
#undef	SQL_DTC_TRANSITION_COST
#undef	SQL_AT_ADD_COLUMN_SINGLE
#undef	SQL_AT_ADD_COLUMN_DEFAULT
#undef	SQL_AT_ADD_COLUMN_COLLATION
#undef	SQL_AT_SET_COLUMN_DEFAULT
#undef	SQL_AT_DROP_COLUMN_DEFAULT
#undef	SQL_AT_DROP_COLUMN_CASCADE
#undef	SQL_AT_DROP_COLUMN_RESTRICT
#undef SQL_AT_ADD_TABLE_CONSTRAINT
#undef SQL_AT_DROP_TABLE_CONSTRAINT_CASCADE
#undef SQL_AT_DROP_TABLE_CONSTRAINT_RESTRICT
#undef SQL_AT_CONSTRAINT_NAME_DEFINITION
#undef SQL_AT_CONSTRAINT_INITIALLY_DEFERRED
#undef SQL_AT_CONSTRAINT_INITIALLY_IMMEDIATE
#undef SQL_AT_CONSTRAINT_DEFERRABLE
#undef SQL_AT_CONSTRAINT_NON_DEFERRABLE
#undef SQL_CVT_CHAR
#undef SQL_CVT_NUMERIC
#undef SQL_CVT_DECIMAL
#undef SQL_CVT_INTEGER
#undef SQL_CVT_SMALLINT
#undef SQL_CVT_FLOAT
#undef SQL_CVT_REAL
#undef SQL_CVT_DOUBLE
#undef SQL_CVT_VARCHAR
#undef SQL_CVT_LONGVARCHAR
#undef SQL_CVT_BINARY
#undef SQL_CVT_VARBINARY
#undef SQL_CVT_BIT
#undef SQL_CVT_TINYINT
#undef SQL_CVT_BIGINT
#undef SQL_CVT_DATE
#undef SQL_CVT_TIME
#undef SQL_CVT_TIMESTAMP
#undef SQL_CVT_LONGVARBINARY
#undef SQL_CVT_INTERVAL_YEAR_MONTH
#undef SQL_CVT_INTERVAL_DAY_TIME
#undef	SQL_CVT_WCHAR
#undef	SQL_CVT_WLONGVARCHAR
#undef	SQL_CVT_WVARCHAR
#undef	SQL_CVT_GUID
#undef SQL_FN_CVT_CONVERT
#undef SQL_FN_CVT_CAST
#undef SQL_FN_STR_CONCAT
#undef SQL_FN_STR_INSERT
#undef SQL_FN_STR_LEFT
#undef SQL_FN_STR_LTRIM
#undef SQL_FN_STR_LENGTH
#undef SQL_FN_STR_LOCATE
#undef SQL_FN_STR_LCASE
#undef SQL_FN_STR_REPEAT
#undef SQL_FN_STR_REPLACE
#undef SQL_FN_STR_RIGHT
#undef SQL_FN_STR_RTRIM
#undef SQL_FN_STR_SUBSTRING
#undef SQL_FN_STR_UCASE
#undef SQL_FN_STR_ASCII
#undef SQL_FN_STR_CHAR
#undef SQL_FN_STR_DIFFERENCE
#undef SQL_FN_STR_LOCATE_2
#undef SQL_FN_STR_SOUNDEX
#undef SQL_FN_STR_SPACE
#undef SQL_FN_STR_BIT_LENGTH
#undef SQL_FN_STR_CHAR_LENGTH
#undef SQL_FN_STR_CHARACTER_LENGTH
#undef SQL_FN_STR_OCTET_LENGTH
#undef SQL_FN_STR_POSITION
#undef SQL_SSF_CONVERT
#undef SQL_SSF_LOWER
#undef SQL_SSF_UPPER
#undef SQL_SSF_SUBSTRING
#undef SQL_SSF_TRANSLATE
#undef SQL_SSF_TRIM_BOTH
#undef SQL_SSF_TRIM_LEADING
#undef SQL_SSF_TRIM_TRAILING
#undef SQL_FN_NUM_ABS
#undef SQL_FN_NUM_ACOS
#undef SQL_FN_NUM_ASIN
#undef SQL_FN_NUM_ATAN
#undef SQL_FN_NUM_ATAN2
#undef SQL_FN_NUM_CEILING
#undef SQL_FN_NUM_COS
#undef SQL_FN_NUM_COT
#undef SQL_FN_NUM_EXP
#undef SQL_FN_NUM_FLOOR
#undef SQL_FN_NUM_LOG
#undef SQL_FN_NUM_MOD
#undef SQL_FN_NUM_SIGN
#undef SQL_FN_NUM_SIN
#undef SQL_FN_NUM_SQRT
#undef SQL_FN_NUM_TAN
#undef SQL_FN_NUM_PI
#undef SQL_FN_NUM_RAND
#undef SQL_FN_NUM_DEGREES
#undef SQL_FN_NUM_LOG10
#undef SQL_FN_NUM_POWER
#undef SQL_FN_NUM_RADIANS
#undef SQL_FN_NUM_ROUND
#undef SQL_FN_NUM_TRUNCATE
#undef SQL_SNVF_BIT_LENGTH
#undef SQL_SNVF_CHAR_LENGTH
#undef SQL_SNVF_CHARACTER_LENGTH
#undef SQL_SNVF_EXTRACT
#undef SQL_SNVF_OCTET_LENGTH
#undef SQL_SNVF_POSITION
#undef SQL_FN_TD_NOW
#undef SQL_FN_TD_CURDATE
#undef SQL_FN_TD_DAYOFMONTH
#undef SQL_FN_TD_DAYOFWEEK
#undef SQL_FN_TD_DAYOFYEAR
#undef SQL_FN_TD_MONTH
#undef SQL_FN_TD_QUARTER
#undef SQL_FN_TD_WEEK
#undef SQL_FN_TD_YEAR
#undef SQL_FN_TD_CURTIME
#undef SQL_FN_TD_HOUR
#undef SQL_FN_TD_MINUTE
#undef SQL_FN_TD_SECOND
#undef SQL_FN_TD_TIMESTAMPADD
#undef SQL_FN_TD_TIMESTAMPDIFF
#undef SQL_FN_TD_DAYNAME
#undef SQL_FN_TD_MONTHNAME
#undef SQL_FN_TD_CURRENT_DATE
#undef SQL_FN_TD_CURRENT_TIME
#undef SQL_FN_TD_CURRENT_TIMESTAMP
#undef SQL_FN_TD_EXTRACT
#undef SQL_SDF_CURRENT_DATE
#undef SQL_SDF_CURRENT_TIME
#undef SQL_SDF_CURRENT_TIMESTAMP
#undef SQL_FN_SYS_USERNAME
#undef SQL_FN_SYS_DBNAME
#undef SQL_FN_SYS_IFNULL
#undef SQL_FN_TSI_FRAC_SECOND
#undef SQL_FN_TSI_SECOND
#undef SQL_FN_TSI_MINUTE
#undef SQL_FN_TSI_HOUR
#undef SQL_FN_TSI_DAY
#undef SQL_FN_TSI_WEEK
#undef SQL_FN_TSI_MONTH
#undef SQL_FN_TSI_QUARTER
#undef SQL_FN_TSI_YEAR
#undef SQL_CA1_NEXT
#undef SQL_CA1_ABSOLUTE
#undef SQL_CA1_RELATIVE
#undef SQL_CA1_BOOKMARK
#undef SQL_CA1_LOCK_NO_CHANGE
#undef SQL_CA1_LOCK_EXCLUSIVE
#undef SQL_CA1_LOCK_UNLOCK
#undef SQL_CA1_POS_POSITION
#undef SQL_CA1_POS_UPDATE
#undef SQL_CA1_POS_DELETE
#undef SQL_CA1_POS_REFRESH
#undef SQL_CA1_POSITIONED_UPDATE
#undef SQL_CA1_POSITIONED_DELETE
#undef SQL_CA1_SELECT_FOR_UPDATE
#undef SQL_CA1_BULK_ADD
#undef SQL_CA1_BULK_UPDATE_BY_BOOKMARK
#undef SQL_CA1_BULK_DELETE_BY_BOOKMARK
#undef SQL_CA1_BULK_FETCH_BY_BOOKMARK
#undef SQL_CA2_READ_ONLY_CONCURRENCY
#undef SQL_CA2_LOCK_CONCURRENCY
#undef SQL_CA2_OPT_ROWVER_CONCURRENCY
#undef SQL_CA2_OPT_VALUES_CONCURRENCY
#undef SQL_CA2_SENSITIVITY_ADDITIONS
#undef SQL_CA2_SENSITIVITY_DELETIONS
#undef SQL_CA2_SENSITIVITY_UPDATES
#undef SQL_CA2_MAX_ROWS_SELECT
#undef SQL_CA2_MAX_ROWS_INSERT
#undef SQL_CA2_MAX_ROWS_DELETE
#undef SQL_CA2_MAX_ROWS_UPDATE
#undef SQL_CA2_MAX_ROWS_CATALOG
#undef SQL_CA2_MAX_ROWS_AFFECTS_ALL
#undef SQL_CA2_CRC_EXACT
#undef SQL_CA2_CRC_APPROXIMATE
#undef SQL_CA2_SIMULATE_NON_UNIQUE
#undef SQL_CA2_SIMULATE_TRY_UNIQUE
#undef SQL_CA2_SIMULATE_UNIQUE
#undef SQL_OAC_NONE
#undef SQL_OAC_LEVEL1
#undef SQL_OAC_LEVEL2
#undef SQL_OSCC_NOT_COMPLIANT
#undef SQL_OSCC_COMPLIANT
#undef SQL_OSC_MINIMUM
#undef SQL_OSC_CORE
#undef SQL_OSC_EXTENDED
#undef SQL_CB_NULL
#undef SQL_CB_NON_NULL
#undef SQL_SO_FORWARD_ONLY
#undef SQL_SO_KEYSET_DRIVEN
#undef SQL_SO_DYNAMIC
#undef SQL_SO_MIXED
#undef SQL_SO_STATIC
#undef SQL_FD_FETCH_RESUME
#undef SQL_FD_FETCH_BOOKMARK
#undef SQL_TXN_VERSIONING
#undef SQL_CN_NONE
#undef SQL_CN_DIFFERENT
#undef SQL_CN_ANY
#undef SQL_NNC_NULL
#undef SQL_NNC_NON_NULL
#undef SQL_NC_START
#undef SQL_NC_END
#undef SQL_FILE_NOT_SUPPORTED
#undef SQL_FILE_TABLE
#undef SQL_FILE_QUALIFIER
#undef SQL_FILE_CATALOG
#undef SQL_GD_BLOCK
#undef SQL_GD_BOUND
#undef SQL_PS_POSITIONED_DELETE
#undef SQL_PS_POSITIONED_UPDATE
#undef SQL_PS_SELECT_FOR_UPDATE
#undef SQL_GB_NOT_SUPPORTED
#undef SQL_GB_GROUP_BY_EQUALS_SELECT
#undef SQL_GB_GROUP_BY_CONTAINS_SELECT
#undef SQL_GB_NO_RELATION
#undef	SQL_GB_COLLATE
#undef SQL_OU_DML_STATEMENTS
#undef SQL_OU_PROCEDURE_INVOCATION
#undef SQL_OU_TABLE_DEFINITION
#undef SQL_OU_INDEX_DEFINITION
#undef SQL_OU_PRIVILEGE_DEFINITION
#undef SQL_SU_DML_STATEMENTS
#undef SQL_SU_PROCEDURE_INVOCATION
#undef SQL_SU_TABLE_DEFINITION
#undef SQL_SU_INDEX_DEFINITION
#undef SQL_SU_PRIVILEGE_DEFINITION
#undef SQL_QU_DML_STATEMENTS
#undef SQL_QU_PROCEDURE_INVOCATION
#undef SQL_QU_TABLE_DEFINITION
#undef SQL_QU_INDEX_DEFINITION
#undef SQL_QU_PRIVILEGE_DEFINITION
#undef SQL_CU_DML_STATEMENTS
#undef SQL_CU_PROCEDURE_INVOCATION
#undef SQL_CU_TABLE_DEFINITION
#undef SQL_CU_INDEX_DEFINITION
#undef SQL_CU_PRIVILEGE_DEFINITION
#undef SQL_SQ_COMPARISON
#undef SQL_SQ_EXISTS
#undef SQL_SQ_IN
#undef SQL_SQ_QUANTIFIED
#undef SQL_SQ_CORRELATED_SUBQUERIES
#undef SQL_U_UNION
#undef SQL_U_UNION_ALL
#undef SQL_BP_CLOSE
#undef SQL_BP_DELETE
#undef SQL_BP_DROP
#undef SQL_BP_TRANSACTION
#undef SQL_BP_UPDATE
#undef SQL_BP_OTHER_HSTMT
#undef SQL_BP_SCROLL
#undef SQL_SS_ADDITIONS
#undef SQL_SS_DELETIONS
#undef SQL_SS_UPDATES
#undef	SQL_CV_CREATE_VIEW
#undef	SQL_CV_CHECK_OPTION
#undef	SQL_CV_CASCADED
#undef	SQL_CV_LOCAL
#undef SQL_LCK_NO_CHANGE
#undef SQL_LCK_EXCLUSIVE
#undef SQL_LCK_UNLOCK
#undef SQL_POS_POSITION
#undef SQL_POS_REFRESH
#undef SQL_POS_UPDATE
#undef SQL_POS_DELETE
#undef SQL_POS_ADD
#undef SQL_QL_START
#undef SQL_QL_END
#undef SQL_AF_AVG
#undef SQL_AF_COUNT
#undef SQL_AF_MAX
#undef SQL_AF_MIN
#undef SQL_AF_SUM
#undef SQL_AF_DISTINCT
#undef SQL_AF_ALL
#undef	SQL_SC_SQL92_ENTRY
#undef	SQL_SC_FIPS127_2_TRANSITIONAL
#undef	SQL_SC_SQL92_INTERMEDIATE
#undef	SQL_SC_SQL92_FULL
#undef SQL_DL_SQL92_DATE
#undef SQL_DL_SQL92_TIME
#undef SQL_DL_SQL92_TIMESTAMP
#undef SQL_DL_SQL92_INTERVAL_YEAR
#undef SQL_DL_SQL92_INTERVAL_MONTH
#undef SQL_DL_SQL92_INTERVAL_DAY
#undef SQL_DL_SQL92_INTERVAL_HOUR
#undef	SQL_DL_SQL92_INTERVAL_MINUTE
#undef SQL_DL_SQL92_INTERVAL_SECOND
#undef SQL_DL_SQL92_INTERVAL_YEAR_TO_MONTH
#undef SQL_DL_SQL92_INTERVAL_DAY_TO_HOUR
#undef SQL_DL_SQL92_INTERVAL_DAY_TO_MINUTE
#undef SQL_DL_SQL92_INTERVAL_DAY_TO_SECOND
#undef SQL_DL_SQL92_INTERVAL_HOUR_TO_MINUTE
#undef SQL_DL_SQL92_INTERVAL_HOUR_TO_SECOND
#undef SQL_DL_SQL92_INTERVAL_MINUTE_TO_SECOND
#undef SQL_CL_START
#undef SQL_CL_END
#undef SQL_BRC_PROCEDURES
#undef	SQL_BRC_EXPLICIT
#undef	SQL_BRC_ROLLED_UP
#undef SQL_BS_SELECT_EXPLICIT
#undef SQL_BS_ROW_COUNT_EXPLICIT
#undef SQL_BS_SELECT_PROC
#undef SQL_BS_ROW_COUNT_PROC
#undef SQL_PARC_BATCH
#undef SQL_PARC_NO_BATCH
#undef SQL_PAS_BATCH
#undef SQL_PAS_NO_BATCH
#undef SQL_PAS_NO_SELECT
#undef SQL_IK_NONE
#undef SQL_IK_ASC
#undef SQL_IK_DESC
#undef SQL_IK_ALL
#undef SQL_ISV_ASSERTIONS
#undef SQL_ISV_CHARACTER_SETS
#undef SQL_ISV_CHECK_CONSTRAINTS
#undef SQL_ISV_COLLATIONS
#undef SQL_ISV_COLUMN_DOMAIN_USAGE
#undef SQL_ISV_COLUMN_PRIVILEGES
#undef SQL_ISV_COLUMNS
#undef SQL_ISV_CONSTRAINT_COLUMN_USAGE
#undef SQL_ISV_CONSTRAINT_TABLE_USAGE
#undef SQL_ISV_DOMAIN_CONSTRAINTS
#undef SQL_ISV_DOMAINS
#undef SQL_ISV_KEY_COLUMN_USAGE
#undef SQL_ISV_REFERENTIAL_CONSTRAINTS
#undef SQL_ISV_SCHEMATA
#undef SQL_ISV_SQL_LANGUAGES
#undef	SQL_ISV_TABLE_CONSTRAINTS
#undef SQL_ISV_TABLE_PRIVILEGES
#undef SQL_ISV_TABLES
#undef SQL_ISV_TRANSLATIONS
#undef SQL_ISV_USAGE_PRIVILEGES
#undef SQL_ISV_VIEW_COLUMN_USAGE
#undef SQL_ISV_VIEW_TABLE_USAGE
#undef SQL_ISV_VIEWS
#undef	SQL_AM_NONE
#undef	SQL_AM_CONNECTION
#undef	SQL_AM_STATEMENT
#undef SQL_AD_CONSTRAINT_NAME_DEFINITION
#undef	SQL_AD_ADD_DOMAIN_CONSTRAINT
#undef	SQL_AD_DROP_DOMAIN_CONSTRAINT
#undef	SQL_AD_ADD_DOMAIN_DEFAULT
#undef	SQL_AD_DROP_DOMAIN_DEFAULT
#undef SQL_AD_ADD_CONSTRAINT_INITIALLY_DEFERRED
#undef SQL_AD_ADD_CONSTRAINT_INITIALLY_IMMEDIATE
#undef SQL_AD_ADD_CONSTRAINT_DEFERRABLE
#undef SQL_AD_ADD_CONSTRAINT_NON_DEFERRABLE
#undef	SQL_CS_CREATE_SCHEMA
#undef	SQL_CS_AUTHORIZATION
#undef	SQL_CS_DEFAULT_CHARACTER_SET
#undef	SQL_CTR_CREATE_TRANSLATION
#undef	SQL_CA_CREATE_ASSERTION
#undef	SQL_CA_CONSTRAINT_INITIALLY_DEFERRED
#undef	SQL_CA_CONSTRAINT_INITIALLY_IMMEDIATE
#undef	SQL_CA_CONSTRAINT_DEFERRABLE
#undef	SQL_CA_CONSTRAINT_NON_DEFERRABLE
#undef	SQL_CCS_CREATE_CHARACTER_SET
#undef	SQL_CCS_COLLATE_CLAUSE
#undef	SQL_CCS_LIMITED_COLLATION
#undef	SQL_CCOL_CREATE_COLLATION
#undef	SQL_CDO_CREATE_DOMAIN
#undef	SQL_CDO_DEFAULT
#undef	SQL_CDO_CONSTRAINT
#undef	SQL_CDO_COLLATION
#undef SQL_CDO_CONSTRAINT_NAME_DEFINITION
#undef SQL_CDO_CONSTRAINT_INITIALLY_DEFERRED
#undef SQL_CDO_CONSTRAINT_INITIALLY_IMMEDIATE
#undef SQL_CDO_CONSTRAINT_DEFERRABLE
#undef SQL_CDO_CONSTRAINT_NON_DEFERRABLE
#undef	SQL_CT_CREATE_TABLE
#undef	SQL_CT_COMMIT_PRESERVE
#undef	SQL_CT_COMMIT_DELETE
#undef	SQL_CT_GLOBAL_TEMPORARY
#undef	SQL_CT_LOCAL_TEMPORARY
#undef	SQL_CT_CONSTRAINT_INITIALLY_DEFERRED
#undef	SQL_CT_CONSTRAINT_INITIALLY_IMMEDIATE
#undef	SQL_CT_CONSTRAINT_DEFERRABLE
#undef	SQL_CT_CONSTRAINT_NON_DEFERRABLE
#undef SQL_CT_COLUMN_CONSTRAINT
#undef SQL_CT_COLUMN_DEFAULT
#undef SQL_CT_COLUMN_COLLATION
#undef SQL_CT_TABLE_CONSTRAINT
#undef SQL_CT_CONSTRAINT_NAME_DEFINITION
#undef SQL_DI_CREATE_INDEX
#undef SQL_DI_DROP_INDEX
#undef	SQL_DC_DROP_COLLATION
#undef	SQL_DD_DROP_DOMAIN
#undef	SQL_DD_RESTRICT
#undef	SQL_DD_CASCADE
#undef	SQL_DS_DROP_SCHEMA
#undef SQL_DS_RESTRICT
#undef	SQL_DS_CASCADE
#undef	SQL_DCS_DROP_CHARACTER_SET
#undef	SQL_DA_DROP_ASSERTION
#undef	SQL_DT_DROP_TABLE
#undef	SQL_DT_RESTRICT
#undef	SQL_DT_CASCADE
#undef	SQL_DTR_DROP_TRANSLATION
#undef	SQL_DV_DROP_VIEW
#undef	SQL_DV_RESTRICT
#undef	SQL_DV_CASCADE
#undef	SQL_IS_INSERT_LITERALS
#undef SQL_IS_INSERT_SEARCHED
#undef SQL_IS_SELECT_INTO
#undef SQL_OIC_CORE
#undef SQL_OIC_LEVEL1
#undef SQL_OIC_LEVEL2
#undef SQL_SFKD_CASCADE
#undef SQL_SFKD_NO_ACTION
#undef SQL_SFKD_SET_DEFAULT
#undef SQL_SFKD_SET_NULL
#undef SQL_SFKU_CASCADE
#undef SQL_SFKU_NO_ACTION
#undef SQL_SFKU_SET_DEFAULT
#undef SQL_SFKU_SET_NULL
#undef SQL_SG_USAGE_ON_DOMAIN
#undef SQL_SG_USAGE_ON_CHARACTER_SET
#undef SQL_SG_USAGE_ON_COLLATION
#undef SQL_SG_USAGE_ON_TRANSLATION
#undef SQL_SG_WITH_GRANT_OPTION
#undef SQL_SG_DELETE_TABLE
#undef SQL_SG_INSERT_TABLE
#undef SQL_SG_INSERT_COLUMN
#undef SQL_SG_REFERENCES_TABLE
#undef SQL_SG_REFERENCES_COLUMN
#undef SQL_SG_SELECT_TABLE
#undef SQL_SG_UPDATE_TABLE
#undef SQL_SG_UPDATE_COLUMN
#undef SQL_SP_EXISTS
#undef SQL_SP_ISNOTNULL
#undef SQL_SP_ISNULL
#undef SQL_SP_MATCH_FULL
#undef SQL_SP_MATCH_PARTIAL
#undef SQL_SP_MATCH_UNIQUE_FULL
#undef SQL_SP_MATCH_UNIQUE_PARTIAL
#undef SQL_SP_OVERLAPS
#undef SQL_SP_UNIQUE
#undef SQL_SP_LIKE
#undef SQL_SP_IN
#undef SQL_SP_BETWEEN
#undef SQL_SP_COMPARISON
#undef SQL_SP_QUANTIFIED_COMPARISON
#undef SQL_SRJO_CORRESPONDING_CLAUSE
#undef SQL_SRJO_CROSS_JOIN
#undef SQL_SRJO_EXCEPT_JOIN
#undef SQL_SRJO_FULL_OUTER_JOIN
#undef SQL_SRJO_INNER_JOIN
#undef SQL_SRJO_INTERSECT_JOIN
#undef SQL_SRJO_LEFT_OUTER_JOIN
#undef SQL_SRJO_NATURAL_JOIN
#undef SQL_SRJO_RIGHT_OUTER_JOIN
#undef SQL_SRJO_UNION_JOIN
#undef SQL_SR_USAGE_ON_DOMAIN
#undef SQL_SR_USAGE_ON_CHARACTER_SET
#undef SQL_SR_USAGE_ON_COLLATION
#undef SQL_SR_USAGE_ON_TRANSLATION
#undef SQL_SR_GRANT_OPTION_FOR
#undef SQL_SR_CASCADE
#undef SQL_SR_RESTRICT
#undef SQL_SR_DELETE_TABLE
#undef SQL_SR_INSERT_TABLE
#undef SQL_SR_INSERT_COLUMN
#undef SQL_SR_REFERENCES_TABLE
#undef SQL_SR_REFERENCES_COLUMN
#undef SQL_SR_SELECT_TABLE
#undef SQL_SR_UPDATE_TABLE
#undef SQL_SR_UPDATE_COLUMN
#undef SQL_SRVC_VALUE_EXPRESSION
#undef SQL_SRVC_NULL
#undef SQL_SRVC_DEFAULT
#undef SQL_SRVC_ROW_SUBQUERY
#undef SQL_SVE_CASE
#undef SQL_SVE_CAST
#undef SQL_SVE_COALESCE
#undef SQL_SVE_NULLIF
#undef SQL_SCC_XOPEN_CLI_VERSION1
#undef SQL_SCC_ISO92_CLI
#undef SQL_US_UNION
#undef SQL_US_UNION_ALL
#undef SQL_DTC_ENLIST_EXPENSIVE
#undef SQL_DTC_UNENLIST_EXPENSIVE
#undef SQL_FETCH_FIRST_USER
#undef SQL_FETCH_FIRST_SYSTEM
#undef SQL_ENTIRE_ROWSET
#undef SQL_POSITION
#undef SQL_REFRESH
#undef SQL_UPDATE
#undef SQL_DELETE
#undef SQL_ADD
#undef	SQL_SETPOS_MAX_OPTION_VALUE
#undef SQL_UPDATE_BY_BOOKMARK
#undef SQL_DELETE_BY_BOOKMARK
#undef	SQL_FETCH_BY_BOOKMARK
#undef SQL_LOCK_NO_CHANGE
#undef SQL_LOCK_EXCLUSIVE
#undef SQL_LOCK_UNLOCK
#undef	SQL_SETPOS_MAX_LOCK_VALUE
#undef SQL_POSITION_TO
#undef SQL_LOCK_RECORD
#undef SQL_REFRESH_RECORD
#undef SQL_UPDATE_RECORD
#undef SQL_DELETE_RECORD
#undef SQL_ADD_RECORD
#undef SQL_BEST_ROWID
#undef SQL_ROWVER
#undef SQL_PC_NOT_PSEUDO
#undef SQL_QUICK
#undef SQL_ENSURE
#undef SQL_TABLE_STAT
#undef SQL_ALL_CATALOGS
#undef SQL_ALL_SCHEMAS
#undef SQL_ALL_TABLE_TYPES
#undef SQL_DRIVER_NOPROMPT
#undef SQL_DRIVER_COMPLETE
#undef SQL_DRIVER_PROMPT
#undef SQL_DRIVER_COMPLETE_REQUIRED
#undef SQL_FETCH_BOOKMARK
#undef SQL_ROW_SUCCESS
#undef SQL_ROW_DELETED
#undef SQL_ROW_UPDATED
#undef SQL_ROW_NOROW
#undef SQL_ROW_ADDED
#undef SQL_ROW_ERROR
#undef SQL_ROW_SUCCESS_WITH_INFO
#undef SQL_ROW_PROCEED
#undef SQL_ROW_IGNORE
#undef SQL_PARAM_SUCCESS
#undef SQL_PARAM_SUCCESS_WITH_INFO
#undef SQL_PARAM_ERROR
#undef SQL_PARAM_UNUSED
#undef SQL_PARAM_DIAG_UNAVAILABLE
#undef SQL_PARAM_PROCEED
#undef SQL_PARAM_IGNORE
#undef SQL_CASCADE
#undef SQL_RESTRICT
#undef SQL_SET_NULL
#undef SQL_NO_ACTION
#undef SQL_SET_DEFAULT
#undef SQL_INITIALLY_DEFERRED
#undef SQL_INITIALLY_IMMEDIATE
#undef SQL_NOT_DEFERRABLE
#undef SQL_PARAM_TYPE_UNKNOWN
#undef SQL_PARAM_INPUT
#undef SQL_PARAM_INPUT_OUTPUT
#undef SQL_RESULT_COL
#undef SQL_PARAM_OUTPUT
#undef SQL_RETURN_VALUE
#undef SQL_PT_UNKNOWN
#undef SQL_PT_PROCEDURE
#undef SQL_PT_FUNCTION
#undef SQL_ODBC_KEYWORDS
#undef SQLAllocHandle
#undef SQLAllocEnv
#undef SQL_YEAR
#undef SQL_MONTH
#undef SQL_DAY
#undef SQL_HOUR
#undef SQL_MINUTE
#undef SQL_SECOND
#undef SQL_YEAR_TO_MONTH
#undef SQL_DAY_TO_HOUR
#undef SQL_DAY_TO_MINUTE
#undef SQL_DAY_TO_SECOND
#undef SQL_HOUR_TO_MINUTE
#undef SQL_HOUR_TO_SECOND
#undef SQL_MINUTE_TO_SECOND
#undef SQL_DATABASE_NAME
#undef SQL_FD_FETCH_PREV
#undef SQL_FETCH_PREV
#undef SQL_CONCUR_TIMESTAMP
#undef SQL_SCCO_OPT_TIMESTAMP
#undef SQL_CC_DELETE
#undef SQL_CR_DELETE
#undef SQL_CC_CLOSE
#undef SQL_CR_CLOSE
#undef SQL_CC_PRESERVE
#undef SQL_CR_PRESERVE
#undef SQL_FETCH_RESUME
#undef SQL_SCROLL_FORWARD_ONLY
#undef SQL_SCROLL_KEYSET_DRIVEN
#undef SQL_SCROLL_DYNAMIC
#undef SQL_SCROLL_STATIC
#undef	TRACE_VERSION
#undef TRACE_ON
#undef TRACE_VS_EVENT_ON
#undef ODBC_VS_FLAG_UNICODE_ARG
#undef	ODBC_VS_FLAG_UNICODE_COR
#undef ODBC_VS_FLAG_RETCODE
#undef ODBC_VS_FLAG_STOP

// undef sqltypes.h artifacts
#undef FAR
#undef CALLBACK
#undef SQL_API
#undef SQL_API
#undef	BOOL
#undef SQLLEN
#undef SQLULEN
#undef SQLSETPOSIROW
#undef SQLLEN
#undef SQLULEN
#undef SQLSETPOSIROW
#undef	__SQLDATE
#undef SQL_MAX_NUMERIC_LEN

// undef sql.h artifacts
#undef SQL_NULL_DATA
#undef SQL_DATA_AT_EXEC
#undef SQL_SUCCESS
#undef SQL_SUCCESS_WITH_INFO
#undef SQL_NO_DATA
#undef SQL_ERROR
#undef SQL_INVALID_HANDLE
#undef SQL_STILL_EXECUTING
#undef SQL_NEED_DATA
#undef SQL_SUCCEEDED
#undef SQL_NTS
#undef SQL_NTSL
#undef SQL_MAX_MESSAGE_LENGTH
#undef SQL_DATE_LEN
#undef SQL_TIME_LEN
#undef SQL_TIMESTAMP_LEN
#undef SQL_HANDLE_ENV
#undef SQL_HANDLE_DBC
#undef SQL_HANDLE_STMT
#undef SQL_HANDLE_DESC
#undef SQL_ATTR_OUTPUT_NTS
#undef SQL_ATTR_AUTO_IPD
#undef SQL_ATTR_METADATA_ID
#undef SQL_ATTR_APP_ROW_DESC
#undef SQL_ATTR_APP_PARAM_DESC
#undef SQL_ATTR_IMP_ROW_DESC
#undef SQL_ATTR_IMP_PARAM_DESC
#undef SQL_ATTR_CURSOR_SCROLLABLE
#undef SQL_ATTR_CURSOR_SENSITIVITY
#undef SQL_NONSCROLLABLE
#undef SQL_SCROLLABLE
#undef SQL_DESC_COUNT
#undef SQL_DESC_TYPE
#undef SQL_DESC_LENGTH
#undef SQL_DESC_OCTET_LENGTH_PTR
#undef SQL_DESC_PRECISION
#undef SQL_DESC_SCALE
#undef SQL_DESC_DATETIME_INTERVAL_CODE
#undef SQL_DESC_NULLABLE
#undef SQL_DESC_INDICATOR_PTR
#undef SQL_DESC_DATA_PTR
#undef SQL_DESC_NAME
#undef SQL_DESC_UNNAMED
#undef SQL_DESC_OCTET_LENGTH
#undef SQL_DESC_ALLOC_TYPE
#undef SQL_DIAG_RETURNCODE
#undef SQL_DIAG_NUMBER
#undef SQL_DIAG_ROW_COUNT
#undef SQL_DIAG_SQLSTATE
#undef SQL_DIAG_NATIVE
#undef SQL_DIAG_MESSAGE_TEXT
#undef SQL_DIAG_DYNAMIC_FUNCTION
#undef SQL_DIAG_CLASS_ORIGIN
#undef SQL_DIAG_SUBCLASS_ORIGIN
#undef SQL_DIAG_CONNECTION_NAME
#undef SQL_DIAG_SERVER_NAME
#undef SQL_DIAG_DYNAMIC_FUNCTION_CODE
#undef SQL_DIAG_ALTER_DOMAIN
#undef SQL_DIAG_ALTER_TABLE
#undef SQL_DIAG_CALL
#undef SQL_DIAG_CREATE_ASSERTION
#undef SQL_DIAG_CREATE_CHARACTER_SET
#undef SQL_DIAG_CREATE_COLLATION
#undef SQL_DIAG_CREATE_DOMAIN
#undef SQL_DIAG_CREATE_INDEX
#undef SQL_DIAG_CREATE_SCHEMA
#undef SQL_DIAG_CREATE_TABLE
#undef SQL_DIAG_CREATE_TRANSLATION
#undef SQL_DIAG_CREATE_VIEW
#undef SQL_DIAG_DELETE_WHERE
#undef	SQL_DIAG_DROP_ASSERTION
#undef	SQL_DIAG_DROP_CHARACTER_SET
#undef	SQL_DIAG_DROP_COLLATION
#undef	SQL_DIAG_DROP_DOMAIN
#undef SQL_DIAG_DROP_INDEX
#undef SQL_DIAG_DROP_SCHEMA
#undef SQL_DIAG_DROP_TABLE
#undef SQL_DIAG_DROP_TRANSLATION
#undef SQL_DIAG_DROP_VIEW
#undef SQL_DIAG_DYNAMIC_DELETE_CURSOR
#undef SQL_DIAG_DYNAMIC_UPDATE_CURSOR
#undef SQL_DIAG_GRANT
#undef SQL_DIAG_INSERT
#undef SQL_DIAG_REVOKE
#undef SQL_DIAG_SELECT_CURSOR
#undef SQL_DIAG_UNKNOWN_STATEMENT
#undef SQL_DIAG_UPDATE_WHERE
#undef	SQL_UNKNOWN_TYPE
#undef SQL_CHAR
#undef SQL_NUMERIC
#undef SQL_DECIMAL
#undef SQL_INTEGER
#undef SQL_SMALLINT
#undef SQL_FLOAT
#undef SQL_REAL
#undef SQL_DOUBLE
#undef SQL_DATETIME
#undef SQL_VARCHAR
#undef SQL_TYPE_DATE
#undef SQL_TYPE_TIME
#undef SQL_TYPE_TIMESTAMP
#undef SQL_UNSPECIFIED
#undef SQL_INSENSITIVE
#undef SQL_SENSITIVE
#undef SQL_ALL_TYPES
#undef SQL_DEFAULT
#undef SQL_ARD_TYPE
#undef SQL_CODE_DATE
#undef SQL_CODE_TIME
#undef SQL_CODE_TIMESTAMP
#undef SQL_FALSE
#undef SQL_TRUE
#undef SQL_NO_NULLS
#undef SQL_NULLABLE
#undef SQL_NULLABLE_UNKNOWN
#undef SQL_PRED_NONE
#undef SQL_PRED_CHAR
#undef SQL_PRED_BASIC
#undef SQL_NAMED
#undef SQL_UNNAMED
#undef SQL_DESC_ALLOC_AUTO
#undef SQL_DESC_ALLOC_USER
#undef SQL_CLOSE
#undef SQL_DROP
#undef SQL_UNBIND
#undef SQL_RESET_PARAMS
#undef SQL_FETCH_NEXT
#undef SQL_FETCH_FIRST
#undef SQL_FETCH_LAST
#undef SQL_FETCH_PRIOR
#undef SQL_FETCH_ABSOLUTE
#undef SQL_FETCH_RELATIVE
#undef SQL_COMMIT
#undef SQL_ROLLBACK
#undef SQL_NULL_HENV
#undef SQL_NULL_HDBC
#undef SQL_NULL_HSTMT
#undef SQL_NULL_HDESC
#undef SQL_NULL_DESC
#undef SQL_NULL_HANDLE
#undef SQL_SCOPE_CURROW
#undef SQL_SCOPE_TRANSACTION
#undef SQL_SCOPE_SESSION
#undef SQL_PC_UNKNOWN
#undef SQL_PC_NON_PSEUDO
#undef SQL_PC_PSEUDO
#undef SQL_ROW_IDENTIFIER
#undef SQL_INDEX_UNIQUE
#undef SQL_INDEX_ALL
#undef SQL_INDEX_CLUSTERED
#undef SQL_INDEX_HASHED
#undef SQL_INDEX_OTHER
#undef SQL_API_SQLALLOCCONNECT
#undef SQL_API_SQLALLOCENV
#undef SQL_API_SQLALLOCHANDLE
#undef SQL_API_SQLALLOCSTMT
#undef SQL_API_SQLBINDCOL
#undef SQL_API_SQLBINDPARAM
#undef SQL_API_SQLCANCEL
#undef SQL_API_SQLCLOSECURSOR
#undef SQL_API_SQLCOLATTRIBUTE
#undef SQL_API_SQLCOLUMNS
#undef SQL_API_SQLCONNECT
#undef SQL_API_SQLCOPYDESC
#undef SQL_API_SQLDATASOURCES
#undef SQL_API_SQLDESCRIBECOL
#undef SQL_API_SQLDISCONNECT
#undef SQL_API_SQLENDTRAN
#undef SQL_API_SQLERROR
#undef SQL_API_SQLEXECDIRECT
#undef SQL_API_SQLEXECUTE
#undef SQL_API_SQLFETCH
#undef SQL_API_SQLFETCHSCROLL
#undef SQL_API_SQLFREECONNECT
#undef SQL_API_SQLFREEENV
#undef SQL_API_SQLFREEHANDLE
#undef SQL_API_SQLFREESTMT
#undef SQL_API_SQLGETCONNECTATTR
#undef SQL_API_SQLGETCONNECTOPTION
#undef SQL_API_SQLGETCURSORNAME
#undef SQL_API_SQLGETDATA
#undef SQL_API_SQLGETDESCFIELD
#undef SQL_API_SQLGETDESCREC
#undef SQL_API_SQLGETDIAGFIELD
#undef SQL_API_SQLGETDIAGREC
#undef SQL_API_SQLGETENVATTR
#undef SQL_API_SQLGETFUNCTIONS
#undef SQL_API_SQLGETINFO
#undef SQL_API_SQLGETSTMTATTR
#undef SQL_API_SQLGETSTMTOPTION
#undef SQL_API_SQLGETTYPEINFO
#undef SQL_API_SQLNUMRESULTCOLS
#undef SQL_API_SQLPARAMDATA
#undef SQL_API_SQLPREPARE
#undef SQL_API_SQLPUTDATA
#undef SQL_API_SQLROWCOUNT
#undef SQL_API_SQLSETCONNECTATTR
#undef SQL_API_SQLSETCONNECTOPTION
#undef SQL_API_SQLSETCURSORNAME
#undef SQL_API_SQLSETDESCFIELD
#undef SQL_API_SQLSETDESCREC
#undef SQL_API_SQLSETENVATTR
#undef SQL_API_SQLSETPARAM
#undef SQL_API_SQLSETSTMTATTR
#undef SQL_API_SQLSETSTMTOPTION
#undef SQL_API_SQLSPECIALCOLUMNS
#undef SQL_API_SQLSTATISTICS
#undef SQL_API_SQLTABLES
#undef SQL_API_SQLTRANSACT
#undef SQL_MAX_DRIVER_CONNECTIONS
#undef SQL_MAXIMUM_DRIVER_CONNECTIONS
#undef SQL_MAX_CONCURRENT_ACTIVITIES
#undef SQL_MAXIMUM_CONCURRENT_ACTIVITIES
#undef SQL_DATA_SOURCE_NAME
#undef SQL_FETCH_DIRECTION
#undef SQL_SERVER_NAME
#undef SQL_SEARCH_PATTERN_ESCAPE
#undef SQL_DBMS_NAME
#undef SQL_DBMS_VER
#undef SQL_ACCESSIBLE_TABLES
#undef SQL_ACCESSIBLE_PROCEDURES
#undef SQL_CURSOR_COMMIT_BEHAVIOR
#undef SQL_DATA_SOURCE_READ_ONLY
#undef SQL_DEFAULT_TXN_ISOLATION
#undef SQL_IDENTIFIER_CASE
#undef SQL_IDENTIFIER_QUOTE_CHAR
#undef SQL_MAX_COLUMN_NAME_LEN
#undef SQL_MAXIMUM_COLUMN_NAME_LENGTH
#undef SQL_MAX_CURSOR_NAME_LEN
#undef SQL_MAXIMUM_CURSOR_NAME_LENGTH
#undef SQL_MAX_SCHEMA_NAME_LEN
#undef SQL_MAXIMUM_SCHEMA_NAME_LENGTH
#undef SQL_MAX_CATALOG_NAME_LEN
#undef SQL_MAXIMUM_CATALOG_NAME_LENGTH
#undef SQL_MAX_TABLE_NAME_LEN
#undef SQL_SCROLL_CONCURRENCY
#undef SQL_TXN_CAPABLE
#undef SQL_TRANSACTION_CAPABLE
#undef SQL_USER_NAME
#undef SQL_TXN_ISOLATION_OPTION
#undef SQL_TRANSACTION_ISOLATION_OPTION
#undef SQL_INTEGRITY
#undef SQL_GETDATA_EXTENSIONS
#undef SQL_NULL_COLLATION
#undef SQL_ALTER_TABLE
#undef SQL_ORDER_BY_COLUMNS_IN_SELECT
#undef SQL_SPECIAL_CHARACTERS
#undef SQL_MAX_COLUMNS_IN_GROUP_BY
#undef SQL_MAXIMUM_COLUMNS_IN_GROUP_BY
#undef SQL_MAX_COLUMNS_IN_INDEX
#undef SQL_MAXIMUM_COLUMNS_IN_INDEX
#undef SQL_MAX_COLUMNS_IN_ORDER_BY
#undef SQL_MAXIMUM_COLUMNS_IN_ORDER_BY
#undef SQL_MAX_COLUMNS_IN_SELECT
#undef SQL_MAXIMUM_COLUMNS_IN_SELECT
#undef SQL_MAX_COLUMNS_IN_TABLE
#undef SQL_MAX_INDEX_SIZE
#undef SQL_MAXIMUM_INDEX_SIZE
#undef SQL_MAX_ROW_SIZE
#undef SQL_MAXIMUM_ROW_SIZE
#undef SQL_MAX_STATEMENT_LEN
#undef SQL_MAXIMUM_STATEMENT_LENGTH
#undef SQL_MAX_TABLES_IN_SELECT
#undef SQL_MAXIMUM_TABLES_IN_SELECT
#undef SQL_MAX_USER_NAME_LEN
#undef SQL_MAXIMUM_USER_NAME_LENGTH
#undef SQL_OJ_CAPABILITIES
#undef SQL_OUTER_JOIN_CAPABILITIES
#undef SQL_XOPEN_CLI_YEAR
#undef SQL_CURSOR_SENSITIVITY
#undef SQL_DESCRIBE_PARAMETER
#undef SQL_CATALOG_NAME
#undef SQL_COLLATION_SEQ
#undef SQL_MAX_IDENTIFIER_LEN
#undef SQL_MAXIMUM_IDENTIFIER_LENGTH
#undef SQL_AT_ADD_COLUMN
#undef SQL_AT_DROP_COLUMN
#undef SQL_AT_ADD_CONSTRAINT
#undef SQL_AM_NONE
#undef SQL_AM_CONNECTION
#undef SQL_AM_STATEMENT
#undef SQL_CB_DELETE
#undef SQL_CB_CLOSE
#undef SQL_CB_PRESERVE
#undef SQL_FD_FETCH_NEXT
#undef SQL_FD_FETCH_FIRST
#undef SQL_FD_FETCH_LAST
#undef SQL_FD_FETCH_PRIOR
#undef SQL_FD_FETCH_ABSOLUTE
#undef SQL_FD_FETCH_RELATIVE
#undef SQL_GD_ANY_COLUMN
#undef SQL_GD_ANY_ORDER
#undef SQL_IC_UPPER
#undef SQL_IC_LOWER
#undef SQL_IC_SENSITIVE
#undef SQL_IC_MIXED
#undef SQL_OJ_LEFT
#undef SQL_OJ_RIGHT
#undef SQL_OJ_FULL
#undef SQL_OJ_NESTED
#undef SQL_OJ_NOT_ORDERED
#undef SQL_OJ_INNER
#undef SQL_OJ_ALL_COMPARISON_OPS
#undef SQL_SCCO_READ_ONLY
#undef SQL_SCCO_LOCK
#undef SQL_SCCO_OPT_ROWVER
#undef SQL_SCCO_OPT_VALUES
#undef SQL_TC_NONE
#undef SQL_TC_DML
#undef SQL_TC_ALL
#undef SQL_TC_DDL_COMMIT
#undef SQL_TC_DDL_IGNORE
#undef SQL_TXN_READ_UNCOMMITTED
#undef SQL_TRANSACTION_READ_UNCOMMITTED
#undef SQL_TXN_READ_COMMITTED
#undef SQL_TRANSACTION_READ_COMMITTED
#undef SQL_TXN_REPEATABLE_READ
#undef SQL_TRANSACTION_REPEATABLE_READ
#undef SQL_TXN_SERIALIZABLE
#undef SQL_TRANSACTION_SERIALIZABLE
#undef SQL_NC_HIGH
#undef SQL_NC_LOW
