# q6.rq — http://www4.wiwiss.fu-berlin.de/bizer/BerlinSPARQLBenchmark/spec/index.html#queryTripleQ6
# $Id: q6.rq,v 1.1 2008-11-10 05:13:42 eric Exp $
# 
# substitutions:
#   %word1%=lipolyses

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>

SELECT ?product ?label
WHERE {
	?product rdfs:label ?label .
 ?product rdf:type bsbm:Product .
	FILTER regex(?label, "lipolyses")
}
