PREFIX sdtm: <http://www.sdtm.org/vocabulary#>
PREFIX spl: <http://www.hl7.org/v3ballot/xml/infrastructure/vocabulary/vocabulary#>

SELECT ?patient ?dob ?sex ?takes ?indicDate # ?indicEnd ?contra
 WHERE {
  ?patient a sdtm:Patient ;
          sdtm:middleName ?middleName ;
          sdtm:dateTimeOfBirth ?dob ;
          sdtm:sex ?sex .

  [	  sdtm:subject ?patient ;
	  sdtm:standardizedMedicationName ?takes ;

	  # nothing by ingredient in sdtm/caBIG/...
	  spl:activeIngredient [ spl:classCode 6809 ] ;
          sdtm:startDateTimeOfMedication ?indicDate
	  # ; sdtm:endDateTimeOfMedication ?indicEnd
  ] .
#  OPTIONAL {
#  [	  sdtm:subject ?patient ;
#	  sdtm:standardizedMedicationName ?contra ;
#	  spl:activeIngredient [ spl:classCode 11289 ]
#         sdtm:effectiveTime [
#         sdtm:startDateTimeOfMedication ?contraDate
#	  # ; sdtm:endDateTimeOfMedication   ?contraEnd
#  ] .
#  }
} LIMIT 30